set SCRIPT_DIR [file dirname [file normalize [info script]]]
set PV_DIR [file normalize [file join $SCRIPT_DIR ..]]
set SETUP_FILE [file join $PV_DIR project_setup.tcl]
set OUT_FILE [file join $SCRIPT_DIR sourceme]

if {![file exists $SETUP_FILE]} {
	put "ERROR: project_setup.tcl not found:"
	put " $SETUP_FILE"
	exit 1
}

source $SETUP_FILE

foreach var {
	HGVAR_DESIGN
	HGVAR_CORES
	HGVAR_SIGNOFF_GDS
	HGVAR_SIGNOFF_NETLIST_PWR
	HGVAR_DRC_RULE_FILE
	HGVAR_LVS_RULE_FILE
	HGVAR_ANT_RULE_FILE
	HGVAR_STDCELL_CDL
	HGVAR_SRAM_CDL
	HGVAR_FLASH_CDL
	HGVAR_LVS_BOX
} {
	if {![info exists $var]} {
		puts "ERROR: $var is not defined in project_setup.tcl"
		exit 1
	}
}

proc bash_quote {s} {
	regsub -all {'} $s {'"'"'} s
	return  "'$s'"
}

proc export_var {OF name valude} {
	put $OF "export $name=[bash_quote $value]"
}

set OF [open $OUT_FILE w]

puts $OF "#!/bin/bash"
puts $OF "#================================================"
puts $OF "# Auto-generated by gen_env.tcl"
puts $OF "# Do not edits this file manually. Edit project_setup.tcl instead."
puts $OF "#================================================"

export_var $OF DESIGN			#HGVAR_DESIGN
export_var $OF CORES			#HGVAR_CORES
export_var $OF GDS_FILE 		#HGVAR_SIGNOFF_GDS
export_var $OF SIGNOFF_NETLIST_PWR	#HGVAR_SIGNOFF_NETLIST_PWR
export_var $OF DRC_DECK			#HGVAR_DRC_RULE_FILE
export_var $OF LVS_DECK 		#HGVAR_LVS_RULE_FILE
export_var $OF ANT_DECK			#HGVAR_ANT_RULE_FILE
export_var $OF LVS_BOX			#HGVAR_LVS_BOX

export_var $OF STDCELL_CDL 	[join #HGVAR_STDCELL_CDL  " "] 
export_var $OF SRAM_CDL 	[join #HGVAR_SRAM_CDL " "]
export_var $OF FLASH_CDL	[join #HGVAR_FLASH_CDL " "]

if {[info exists ASAP7_CDL_DIR]} {
	export_var $OF ASAP7_CDL_DIR $ ASAP7_CDL_DIR
}

close $OF

file attributes $OUT_FILE -permissions u+rwx,g+rx,o+rx

puts "================================================"
puts "Generated inviroment file:"
puts " $OUT_FILE"
puts "================================================"
puts "Design			=$HGVAR_DESIGN"
puts "Core 			=$HGVAR_CORES"
puts "GDS_FILE			=$HGVAR_SIGNOFF_GDS"
puts "SIGNOFF_NETLIST_PWR 	=$HGVAR_SIGNOFF_NETLIST_PWR"
puts "DRC_DECK			=$HGVAR_DRC_RULE_FILE"
puts "LVS_DECK			=$HGVAR_LVS_RULE_FILE"
puts "ANT_DECK			=$HGVAR_ANT_RULE_FILE"
puts "LVS_BOX			=$HGVAR_LVS_BOX"
puts "================================================"

exit 0
