###############################################################
#  Generated by:      Cadence Innovus 23.14-s088_1
#  OS:                Linux x86_64(Host ID user1-EliteMini)
#  Generated on:      Sun Jul 19 00:51:38 2026
#  Design:            Multiplier32
#  Command:           create_ccopt_clock_tree_spec -filename ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin iclk true

# Clocks present at pin iclk
#   CLK (period 1000.0ps) in timing_config mode_normal([./outputs/Mul32_syn.sdc])
create_ccopt_clock_tree -name CLK -source iclk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner corner -early -clock_tree CLK 10.0
set_ccopt_property target_max_trans_sdc -delay_corner corner -late -clock_tree CLK 40.0
# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -delay_corner corner -early -rise -clock_tree CLK 100.0
set_ccopt_property source_latency -delay_corner corner -early -fall -clock_tree CLK 100.0
set_ccopt_property source_latency -delay_corner corner -late -rise -clock_tree CLK 150.0
set_ccopt_property source_latency -delay_corner corner -late -fall -clock_tree CLK 150.0
# Clock period setting for source pin of CLK
set_ccopt_property clock_period -pin iclk 1000

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:CLK in timing_config:mode_normal (sdc ./outputs/Mul32_syn.sdc)
create_ccopt_skew_group -name CLK/mode_normal -sources iclk -auto_sinks
set_ccopt_property include_source_latency -skew_group CLK/mode_normal true
set_ccopt_property extracted_from_clock_name -skew_group CLK/mode_normal CLK
set_ccopt_property extracted_from_constraint_mode_names -skew_group CLK/mode_normal {mode_normal  }
set_ccopt_property extracted_from_delay_corners -skew_group CLK/mode_normal corner


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

