###############################################################
#  Generated by:      Cadence Innovus 23.14-s088_1
#  OS:                Linux x86_64(Host ID user1-EliteMini)
#  Generated on:      Fri Aug  7 00:09:59 2026
#  Design:            axi_ram
#  Command:           saveDesign ./saved/axi_ram_placed.e
###############################################################
if {[is_common_ui_mode]} {
  read_db [file dirname [file normalize [info script]]]/axi_ram_placed.e.dat
} else {
  restoreDesign [file dirname [file normalize [info script]]]/axi_ram_placed.e.dat axi_ram
}

