
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point s_axi_awid[4] s_axi_awid[4] -type PI PI
add mapped point s_axi_awid[3] s_axi_awid[3] -type PI PI
add mapped point s_axi_awid[2] s_axi_awid[2] -type PI PI
add mapped point s_axi_awid[1] s_axi_awid[1] -type PI PI
add mapped point s_axi_awid[0] s_axi_awid[0] -type PI PI
add mapped point s_axi_awaddr[31] s_axi_awaddr[31] -type PI PI
add mapped point s_axi_awaddr[30] s_axi_awaddr[30] -type PI PI
add mapped point s_axi_awaddr[29] s_axi_awaddr[29] -type PI PI
add mapped point s_axi_awaddr[28] s_axi_awaddr[28] -type PI PI
add mapped point s_axi_awaddr[27] s_axi_awaddr[27] -type PI PI
add mapped point s_axi_awaddr[26] s_axi_awaddr[26] -type PI PI
add mapped point s_axi_awaddr[25] s_axi_awaddr[25] -type PI PI
add mapped point s_axi_awaddr[24] s_axi_awaddr[24] -type PI PI
add mapped point s_axi_awaddr[23] s_axi_awaddr[23] -type PI PI
add mapped point s_axi_awaddr[22] s_axi_awaddr[22] -type PI PI
add mapped point s_axi_awaddr[21] s_axi_awaddr[21] -type PI PI
add mapped point s_axi_awaddr[20] s_axi_awaddr[20] -type PI PI
add mapped point s_axi_awaddr[19] s_axi_awaddr[19] -type PI PI
add mapped point s_axi_awaddr[18] s_axi_awaddr[18] -type PI PI
add mapped point s_axi_awaddr[17] s_axi_awaddr[17] -type PI PI
add mapped point s_axi_awaddr[16] s_axi_awaddr[16] -type PI PI
add mapped point s_axi_awaddr[15] s_axi_awaddr[15] -type PI PI
add mapped point s_axi_awaddr[14] s_axi_awaddr[14] -type PI PI
add mapped point s_axi_awaddr[13] s_axi_awaddr[13] -type PI PI
add mapped point s_axi_awaddr[12] s_axi_awaddr[12] -type PI PI
add mapped point s_axi_awaddr[11] s_axi_awaddr[11] -type PI PI
add mapped point s_axi_awaddr[10] s_axi_awaddr[10] -type PI PI
add mapped point s_axi_awaddr[9] s_axi_awaddr[9] -type PI PI
add mapped point s_axi_awaddr[8] s_axi_awaddr[8] -type PI PI
add mapped point s_axi_awaddr[7] s_axi_awaddr[7] -type PI PI
add mapped point s_axi_awaddr[6] s_axi_awaddr[6] -type PI PI
add mapped point s_axi_awaddr[5] s_axi_awaddr[5] -type PI PI
add mapped point s_axi_awaddr[4] s_axi_awaddr[4] -type PI PI
add mapped point s_axi_awaddr[3] s_axi_awaddr[3] -type PI PI
add mapped point s_axi_awaddr[2] s_axi_awaddr[2] -type PI PI
add mapped point s_axi_awaddr[1] s_axi_awaddr[1] -type PI PI
add mapped point s_axi_awaddr[0] s_axi_awaddr[0] -type PI PI
add mapped point s_axi_awlen[7] s_axi_awlen[7] -type PI PI
add mapped point s_axi_awlen[6] s_axi_awlen[6] -type PI PI
add mapped point s_axi_awlen[5] s_axi_awlen[5] -type PI PI
add mapped point s_axi_awlen[4] s_axi_awlen[4] -type PI PI
add mapped point s_axi_awlen[3] s_axi_awlen[3] -type PI PI
add mapped point s_axi_awlen[2] s_axi_awlen[2] -type PI PI
add mapped point s_axi_awlen[1] s_axi_awlen[1] -type PI PI
add mapped point s_axi_awlen[0] s_axi_awlen[0] -type PI PI
add mapped point s_axi_awsize[2] s_axi_awsize[2] -type PI PI
add mapped point s_axi_awsize[1] s_axi_awsize[1] -type PI PI
add mapped point s_axi_awsize[0] s_axi_awsize[0] -type PI PI
add mapped point s_axi_awburst[1] s_axi_awburst[1] -type PI PI
add mapped point s_axi_awburst[0] s_axi_awburst[0] -type PI PI
add mapped point s_axi_awlock s_axi_awlock -type PI PI
add mapped point s_axi_awcache[3] s_axi_awcache[3] -type PI PI
add mapped point s_axi_awcache[2] s_axi_awcache[2] -type PI PI
add mapped point s_axi_awcache[1] s_axi_awcache[1] -type PI PI
add mapped point s_axi_awcache[0] s_axi_awcache[0] -type PI PI
add mapped point s_axi_awprot[2] s_axi_awprot[2] -type PI PI
add mapped point s_axi_awprot[1] s_axi_awprot[1] -type PI PI
add mapped point s_axi_awprot[0] s_axi_awprot[0] -type PI PI
add mapped point s_axi_awqos[3] s_axi_awqos[3] -type PI PI
add mapped point s_axi_awqos[2] s_axi_awqos[2] -type PI PI
add mapped point s_axi_awqos[1] s_axi_awqos[1] -type PI PI
add mapped point s_axi_awqos[0] s_axi_awqos[0] -type PI PI
add mapped point s_axi_awregion[3] s_axi_awregion[3] -type PI PI
add mapped point s_axi_awregion[2] s_axi_awregion[2] -type PI PI
add mapped point s_axi_awregion[1] s_axi_awregion[1] -type PI PI
add mapped point s_axi_awregion[0] s_axi_awregion[0] -type PI PI
add mapped point s_axi_awvalid s_axi_awvalid -type PI PI
add mapped point s_axi_wdata[31] s_axi_wdata[31] -type PI PI
add mapped point s_axi_wdata[30] s_axi_wdata[30] -type PI PI
add mapped point s_axi_wdata[29] s_axi_wdata[29] -type PI PI
add mapped point s_axi_wdata[28] s_axi_wdata[28] -type PI PI
add mapped point s_axi_wdata[27] s_axi_wdata[27] -type PI PI
add mapped point s_axi_wdata[26] s_axi_wdata[26] -type PI PI
add mapped point s_axi_wdata[25] s_axi_wdata[25] -type PI PI
add mapped point s_axi_wdata[24] s_axi_wdata[24] -type PI PI
add mapped point s_axi_wdata[23] s_axi_wdata[23] -type PI PI
add mapped point s_axi_wdata[22] s_axi_wdata[22] -type PI PI
add mapped point s_axi_wdata[21] s_axi_wdata[21] -type PI PI
add mapped point s_axi_wdata[20] s_axi_wdata[20] -type PI PI
add mapped point s_axi_wdata[19] s_axi_wdata[19] -type PI PI
add mapped point s_axi_wdata[18] s_axi_wdata[18] -type PI PI
add mapped point s_axi_wdata[17] s_axi_wdata[17] -type PI PI
add mapped point s_axi_wdata[16] s_axi_wdata[16] -type PI PI
add mapped point s_axi_wdata[15] s_axi_wdata[15] -type PI PI
add mapped point s_axi_wdata[14] s_axi_wdata[14] -type PI PI
add mapped point s_axi_wdata[13] s_axi_wdata[13] -type PI PI
add mapped point s_axi_wdata[12] s_axi_wdata[12] -type PI PI
add mapped point s_axi_wdata[11] s_axi_wdata[11] -type PI PI
add mapped point s_axi_wdata[10] s_axi_wdata[10] -type PI PI
add mapped point s_axi_wdata[9] s_axi_wdata[9] -type PI PI
add mapped point s_axi_wdata[8] s_axi_wdata[8] -type PI PI
add mapped point s_axi_wdata[7] s_axi_wdata[7] -type PI PI
add mapped point s_axi_wdata[6] s_axi_wdata[6] -type PI PI
add mapped point s_axi_wdata[5] s_axi_wdata[5] -type PI PI
add mapped point s_axi_wdata[4] s_axi_wdata[4] -type PI PI
add mapped point s_axi_wdata[3] s_axi_wdata[3] -type PI PI
add mapped point s_axi_wdata[2] s_axi_wdata[2] -type PI PI
add mapped point s_axi_wdata[1] s_axi_wdata[1] -type PI PI
add mapped point s_axi_wdata[0] s_axi_wdata[0] -type PI PI
add mapped point s_axi_wstrb[3] s_axi_wstrb[3] -type PI PI
add mapped point s_axi_wstrb[2] s_axi_wstrb[2] -type PI PI
add mapped point s_axi_wstrb[1] s_axi_wstrb[1] -type PI PI
add mapped point s_axi_wstrb[0] s_axi_wstrb[0] -type PI PI
add mapped point s_axi_wlast s_axi_wlast -type PI PI
add mapped point s_axi_wvalid s_axi_wvalid -type PI PI
add mapped point s_axi_bready s_axi_bready -type PI PI
add mapped point s_axi_arid[4] s_axi_arid[4] -type PI PI
add mapped point s_axi_arid[3] s_axi_arid[3] -type PI PI
add mapped point s_axi_arid[2] s_axi_arid[2] -type PI PI
add mapped point s_axi_arid[1] s_axi_arid[1] -type PI PI
add mapped point s_axi_arid[0] s_axi_arid[0] -type PI PI
add mapped point s_axi_araddr[31] s_axi_araddr[31] -type PI PI
add mapped point s_axi_araddr[30] s_axi_araddr[30] -type PI PI
add mapped point s_axi_araddr[29] s_axi_araddr[29] -type PI PI
add mapped point s_axi_araddr[28] s_axi_araddr[28] -type PI PI
add mapped point s_axi_araddr[27] s_axi_araddr[27] -type PI PI
add mapped point s_axi_araddr[26] s_axi_araddr[26] -type PI PI
add mapped point s_axi_araddr[25] s_axi_araddr[25] -type PI PI
add mapped point s_axi_araddr[24] s_axi_araddr[24] -type PI PI
add mapped point s_axi_araddr[23] s_axi_araddr[23] -type PI PI
add mapped point s_axi_araddr[22] s_axi_araddr[22] -type PI PI
add mapped point s_axi_araddr[21] s_axi_araddr[21] -type PI PI
add mapped point s_axi_araddr[20] s_axi_araddr[20] -type PI PI
add mapped point s_axi_araddr[19] s_axi_araddr[19] -type PI PI
add mapped point s_axi_araddr[18] s_axi_araddr[18] -type PI PI
add mapped point s_axi_araddr[17] s_axi_araddr[17] -type PI PI
add mapped point s_axi_araddr[16] s_axi_araddr[16] -type PI PI
add mapped point s_axi_araddr[15] s_axi_araddr[15] -type PI PI
add mapped point s_axi_araddr[14] s_axi_araddr[14] -type PI PI
add mapped point s_axi_araddr[13] s_axi_araddr[13] -type PI PI
add mapped point s_axi_araddr[12] s_axi_araddr[12] -type PI PI
add mapped point s_axi_araddr[11] s_axi_araddr[11] -type PI PI
add mapped point s_axi_araddr[10] s_axi_araddr[10] -type PI PI
add mapped point s_axi_araddr[9] s_axi_araddr[9] -type PI PI
add mapped point s_axi_araddr[8] s_axi_araddr[8] -type PI PI
add mapped point s_axi_araddr[7] s_axi_araddr[7] -type PI PI
add mapped point s_axi_araddr[6] s_axi_araddr[6] -type PI PI
add mapped point s_axi_araddr[5] s_axi_araddr[5] -type PI PI
add mapped point s_axi_araddr[4] s_axi_araddr[4] -type PI PI
add mapped point s_axi_araddr[3] s_axi_araddr[3] -type PI PI
add mapped point s_axi_araddr[2] s_axi_araddr[2] -type PI PI
add mapped point s_axi_araddr[1] s_axi_araddr[1] -type PI PI
add mapped point s_axi_araddr[0] s_axi_araddr[0] -type PI PI
add mapped point s_axi_arlen[7] s_axi_arlen[7] -type PI PI
add mapped point s_axi_arlen[6] s_axi_arlen[6] -type PI PI
add mapped point s_axi_arlen[5] s_axi_arlen[5] -type PI PI
add mapped point s_axi_arlen[4] s_axi_arlen[4] -type PI PI
add mapped point s_axi_arlen[3] s_axi_arlen[3] -type PI PI
add mapped point s_axi_arlen[2] s_axi_arlen[2] -type PI PI
add mapped point s_axi_arlen[1] s_axi_arlen[1] -type PI PI
add mapped point s_axi_arlen[0] s_axi_arlen[0] -type PI PI
add mapped point s_axi_arsize[2] s_axi_arsize[2] -type PI PI
add mapped point s_axi_arsize[1] s_axi_arsize[1] -type PI PI
add mapped point s_axi_arsize[0] s_axi_arsize[0] -type PI PI
add mapped point s_axi_arburst[1] s_axi_arburst[1] -type PI PI
add mapped point s_axi_arburst[0] s_axi_arburst[0] -type PI PI
add mapped point s_axi_arlock s_axi_arlock -type PI PI
add mapped point s_axi_arcache[3] s_axi_arcache[3] -type PI PI
add mapped point s_axi_arcache[2] s_axi_arcache[2] -type PI PI
add mapped point s_axi_arcache[1] s_axi_arcache[1] -type PI PI
add mapped point s_axi_arcache[0] s_axi_arcache[0] -type PI PI
add mapped point s_axi_arprot[2] s_axi_arprot[2] -type PI PI
add mapped point s_axi_arprot[1] s_axi_arprot[1] -type PI PI
add mapped point s_axi_arprot[0] s_axi_arprot[0] -type PI PI
add mapped point s_axi_arqos[3] s_axi_arqos[3] -type PI PI
add mapped point s_axi_arqos[2] s_axi_arqos[2] -type PI PI
add mapped point s_axi_arqos[1] s_axi_arqos[1] -type PI PI
add mapped point s_axi_arqos[0] s_axi_arqos[0] -type PI PI
add mapped point s_axi_arregion[3] s_axi_arregion[3] -type PI PI
add mapped point s_axi_arregion[2] s_axi_arregion[2] -type PI PI
add mapped point s_axi_arregion[1] s_axi_arregion[1] -type PI PI
add mapped point s_axi_arregion[0] s_axi_arregion[0] -type PI PI
add mapped point s_axi_arvalid s_axi_arvalid -type PI PI
add mapped point s_axi_rready s_axi_rready -type PI PI

//output ports
add mapped point s_axi_awready s_axi_awready -type PO PO
add mapped point s_axi_wready s_axi_wready -type PO PO
add mapped point s_axi_bid[4] s_axi_bid[4] -type PO PO
add mapped point s_axi_bid[3] s_axi_bid[3] -type PO PO
add mapped point s_axi_bid[2] s_axi_bid[2] -type PO PO
add mapped point s_axi_bid[1] s_axi_bid[1] -type PO PO
add mapped point s_axi_bid[0] s_axi_bid[0] -type PO PO
add mapped point s_axi_bresp[1] s_axi_bresp[1] -type PO PO
add mapped point s_axi_bresp[0] s_axi_bresp[0] -type PO PO
add mapped point s_axi_bvalid s_axi_bvalid -type PO PO
add mapped point s_axi_arready s_axi_arready -type PO PO
add mapped point s_axi_rid[4] s_axi_rid[4] -type PO PO
add mapped point s_axi_rid[3] s_axi_rid[3] -type PO PO
add mapped point s_axi_rid[2] s_axi_rid[2] -type PO PO
add mapped point s_axi_rid[1] s_axi_rid[1] -type PO PO
add mapped point s_axi_rid[0] s_axi_rid[0] -type PO PO
add mapped point s_axi_rdata[31] s_axi_rdata[31] -type PO PO
add mapped point s_axi_rdata[30] s_axi_rdata[30] -type PO PO
add mapped point s_axi_rdata[29] s_axi_rdata[29] -type PO PO
add mapped point s_axi_rdata[28] s_axi_rdata[28] -type PO PO
add mapped point s_axi_rdata[27] s_axi_rdata[27] -type PO PO
add mapped point s_axi_rdata[26] s_axi_rdata[26] -type PO PO
add mapped point s_axi_rdata[25] s_axi_rdata[25] -type PO PO
add mapped point s_axi_rdata[24] s_axi_rdata[24] -type PO PO
add mapped point s_axi_rdata[23] s_axi_rdata[23] -type PO PO
add mapped point s_axi_rdata[22] s_axi_rdata[22] -type PO PO
add mapped point s_axi_rdata[21] s_axi_rdata[21] -type PO PO
add mapped point s_axi_rdata[20] s_axi_rdata[20] -type PO PO
add mapped point s_axi_rdata[19] s_axi_rdata[19] -type PO PO
add mapped point s_axi_rdata[18] s_axi_rdata[18] -type PO PO
add mapped point s_axi_rdata[17] s_axi_rdata[17] -type PO PO
add mapped point s_axi_rdata[16] s_axi_rdata[16] -type PO PO
add mapped point s_axi_rdata[15] s_axi_rdata[15] -type PO PO
add mapped point s_axi_rdata[14] s_axi_rdata[14] -type PO PO
add mapped point s_axi_rdata[13] s_axi_rdata[13] -type PO PO
add mapped point s_axi_rdata[12] s_axi_rdata[12] -type PO PO
add mapped point s_axi_rdata[11] s_axi_rdata[11] -type PO PO
add mapped point s_axi_rdata[10] s_axi_rdata[10] -type PO PO
add mapped point s_axi_rdata[9] s_axi_rdata[9] -type PO PO
add mapped point s_axi_rdata[8] s_axi_rdata[8] -type PO PO
add mapped point s_axi_rdata[7] s_axi_rdata[7] -type PO PO
add mapped point s_axi_rdata[6] s_axi_rdata[6] -type PO PO
add mapped point s_axi_rdata[5] s_axi_rdata[5] -type PO PO
add mapped point s_axi_rdata[4] s_axi_rdata[4] -type PO PO
add mapped point s_axi_rdata[3] s_axi_rdata[3] -type PO PO
add mapped point s_axi_rdata[2] s_axi_rdata[2] -type PO PO
add mapped point s_axi_rdata[1] s_axi_rdata[1] -type PO PO
add mapped point s_axi_rdata[0] s_axi_rdata[0] -type PO PO
add mapped point s_axi_rresp[1] s_axi_rresp[1] -type PO PO
add mapped point s_axi_rresp[0] s_axi_rresp[0] -type PO PO
add mapped point s_axi_rlast s_axi_rlast -type PO PO
add mapped point s_axi_rvalid s_axi_rvalid -type PO PO

//inout ports




//Sequential Pins
add mapped point u_mem/read_bank_q[0]/q u_mem/read_bank_q_reg[0]/QN -type DFF DFF
add mapped point u_mem/read_bank_q[1]/q u_mem/read_bank_q_reg[1]/QN -type DFF DFF
add mapped point u_mem/read_bank_q[2]/q u_mem/read_bank_q_reg[2]/QN -type DFF DFF
add mapped point u_mem/read_bank_q[3]/q u_mem/read_bank_q_reg[3]/QN -type DFF DFF
add mapped point r_addr_reg[2]/q r_addr_reg_reg[2]/QN -type DFF DFF
add mapped point r_addr_reg[3]/q r_addr_reg_reg[3]/QN -type DFF DFF
add mapped point r_addr_reg[4]/q r_addr_reg_reg[4]/QN -type DFF DFF
add mapped point r_addr_reg[5]/q r_addr_reg_reg[5]/QN -type DFF DFF
add mapped point r_addr_reg[6]/q r_addr_reg_reg[6]/QN -type DFF DFF
add mapped point r_addr_reg[7]/q r_addr_reg_reg[7]/QN -type DFF DFF
add mapped point r_addr_reg[8]/q r_addr_reg_reg[8]/QN -type DFF DFF
add mapped point r_addr_reg[9]/q r_addr_reg_reg[9]/QN -type DFF DFF
add mapped point r_addr_reg[10]/q r_addr_reg_reg[10]/QN -type DFF DFF
add mapped point r_addr_reg[11]/q r_addr_reg_reg[11]/QN -type DFF DFF
add mapped point r_addr_reg[12]/q r_addr_reg_reg[12]/QN -type DFF DFF
add mapped point r_addr_reg[13]/q r_addr_reg_reg[13]/QN -type DFF DFF
add mapped point r_addr_reg[14]/q r_addr_reg_reg[14]/QN -type DFF DFF
add mapped point r_addr_reg[15]/q r_addr_reg_reg[15]/QN -type DFF DFF
add mapped point r_count_reg[0]/q r_count_reg_reg[0]/QN -type DFF DFF
add mapped point r_count_reg[1]/q r_count_reg_reg[1]/QN -type DFF DFF
add mapped point r_count_reg[2]/q r_count_reg_reg[2]/QN -type DFF DFF
add mapped point r_count_reg[3]/q r_count_reg_reg[3]/QN -type DFF DFF
add mapped point r_count_reg[4]/q r_count_reg_reg[4]/QN -type DFF DFF
add mapped point r_count_reg[5]/q r_count_reg_reg[5]/QN -type DFF DFF
add mapped point r_count_reg[6]/q r_count_reg_reg[6]/QN -type DFF DFF
add mapped point r_count_reg[7]/q r_count_reg_reg[7]/QN -type DFF DFF
add mapped point r_error_reg/q r_error_reg_reg/QN -type DFF DFF
add mapped point r_id_reg[0]/q r_id_reg_reg[0]/QN -type DFF DFF
add mapped point r_id_reg[1]/q r_id_reg_reg[1]/QN -type DFF DFF
add mapped point r_id_reg[2]/q r_id_reg_reg[2]/QN -type DFF DFF
add mapped point r_id_reg[3]/q r_id_reg_reg[3]/QN -type DFF DFF
add mapped point r_id_reg[4]/q r_id_reg_reg[4]/QN -type DFF DFF
add mapped point r_incr_reg/q r_incr_reg_reg/QN -type DFF DFF
add mapped point r_len_reg[0]/q r_len_reg_reg[0]/QN -type DFF DFF
add mapped point r_len_reg[1]/q r_len_reg_reg[1]/QN -type DFF DFF
add mapped point r_len_reg[2]/q r_len_reg_reg[2]/QN -type DFF DFF
add mapped point r_len_reg[3]/q r_len_reg_reg[3]/QN -type DFF DFF
add mapped point r_len_reg[4]/q r_len_reg_reg[4]/QN -type DFF DFF
add mapped point r_len_reg[5]/q r_len_reg_reg[5]/QN -type DFF DFF
add mapped point r_len_reg[6]/q r_len_reg_reg[6]/QN -type DFF DFF
add mapped point r_len_reg[7]/q r_len_reg_reg[7]/QN -type DFF DFF
add mapped point s_axi_arready/q s_axi_arready_reg/QN -type DFF DFF
add mapped point s_axi_bid[0]/q s_axi_bid_reg[0]/QN -type DFF DFF
add mapped point s_axi_bid[1]/q s_axi_bid_reg[1]/QN -type DFF DFF
add mapped point s_axi_bid[2]/q s_axi_bid_reg[2]/QN -type DFF DFF
add mapped point s_axi_bid[3]/q s_axi_bid_reg[3]/QN -type DFF DFF
add mapped point s_axi_bid[4]/q s_axi_bid_reg[4]/QN -type DFF DFF
add mapped point s_axi_bresp[1]/q s_axi_bresp_reg[1]/QN -type DFF DFF
add mapped point s_axi_bvalid/q s_axi_bvalid_reg/QN -type DFF DFF
add mapped point s_axi_rdata[0]/q s_axi_rdata_reg[0]/QN -type DFF DFF
add mapped point s_axi_rdata[1]/q s_axi_rdata_reg[1]/QN -type DFF DFF
add mapped point s_axi_rdata[2]/q s_axi_rdata_reg[2]/QN -type DFF DFF
add mapped point s_axi_rdata[3]/q s_axi_rdata_reg[3]/QN -type DFF DFF
add mapped point s_axi_rdata[4]/q s_axi_rdata_reg[4]/QN -type DFF DFF
add mapped point s_axi_rdata[5]/q s_axi_rdata_reg[5]/QN -type DFF DFF
add mapped point s_axi_rdata[6]/q s_axi_rdata_reg[6]/QN -type DFF DFF
add mapped point s_axi_rdata[7]/q s_axi_rdata_reg[7]/QN -type DFF DFF
add mapped point s_axi_rdata[8]/q s_axi_rdata_reg[8]/QN -type DFF DFF
add mapped point s_axi_rdata[9]/q s_axi_rdata_reg[9]/QN -type DFF DFF
add mapped point s_axi_rdata[10]/q s_axi_rdata_reg[10]/QN -type DFF DFF
add mapped point s_axi_rdata[11]/q s_axi_rdata_reg[11]/QN -type DFF DFF
add mapped point s_axi_rdata[12]/q s_axi_rdata_reg[12]/QN -type DFF DFF
add mapped point s_axi_rdata[13]/q s_axi_rdata_reg[13]/QN -type DFF DFF
add mapped point s_axi_rdata[14]/q s_axi_rdata_reg[14]/QN -type DFF DFF
add mapped point s_axi_rdata[15]/q s_axi_rdata_reg[15]/QN -type DFF DFF
add mapped point s_axi_rdata[16]/q s_axi_rdata_reg[16]/QN -type DFF DFF
add mapped point s_axi_rdata[17]/q s_axi_rdata_reg[17]/QN -type DFF DFF
add mapped point s_axi_rdata[18]/q s_axi_rdata_reg[18]/QN -type DFF DFF
add mapped point s_axi_rdata[19]/q s_axi_rdata_reg[19]/QN -type DFF DFF
add mapped point s_axi_rdata[20]/q s_axi_rdata_reg[20]/QN -type DFF DFF
add mapped point s_axi_rdata[21]/q s_axi_rdata_reg[21]/QN -type DFF DFF
add mapped point s_axi_rdata[22]/q s_axi_rdata_reg[22]/QN -type DFF DFF
add mapped point s_axi_rdata[23]/q s_axi_rdata_reg[23]/QN -type DFF DFF
add mapped point s_axi_rdata[24]/q s_axi_rdata_reg[24]/QN -type DFF DFF
add mapped point s_axi_rdata[25]/q s_axi_rdata_reg[25]/QN -type DFF DFF
add mapped point s_axi_rdata[26]/q s_axi_rdata_reg[26]/QN -type DFF DFF
add mapped point s_axi_rdata[27]/q s_axi_rdata_reg[27]/QN -type DFF DFF
add mapped point s_axi_rdata[28]/q s_axi_rdata_reg[28]/QN -type DFF DFF
add mapped point s_axi_rdata[29]/q s_axi_rdata_reg[29]/QN -type DFF DFF
add mapped point s_axi_rdata[30]/q s_axi_rdata_reg[30]/QN -type DFF DFF
add mapped point s_axi_rdata[31]/q s_axi_rdata_reg[31]/QN -type DFF DFF
add mapped point s_axi_rlast/q s_axi_rlast_reg/QN -type DFF DFF
add mapped point s_axi_rresp[1]/q s_axi_rresp_reg[1]/QN -type DFF DFF
add mapped point s_axi_rvalid/q s_axi_rvalid_reg/QN -type DFF DFF
add mapped point s_axi_wready/q s_axi_wready_reg/QN -type DFF DFF
add mapped point state[0]/q state_reg[0]/QN -type DFF DFF
add mapped point state[1]/q state_reg[1]/QN -type DFF DFF
add mapped point state[2]/q state_reg[2]/QN -type DFF DFF
add mapped point state[3]/q state_reg[3]/QN -type DFF DFF
add mapped point w_addr_reg[2]/q w_addr_reg_reg[2]/QN -type DFF DFF
add mapped point w_addr_reg[3]/q w_addr_reg_reg[3]/QN -type DFF DFF
add mapped point w_addr_reg[4]/q w_addr_reg_reg[4]/QN -type DFF DFF
add mapped point w_addr_reg[5]/q w_addr_reg_reg[5]/QN -type DFF DFF
add mapped point w_addr_reg[6]/q w_addr_reg_reg[6]/QN -type DFF DFF
add mapped point w_addr_reg[7]/q w_addr_reg_reg[7]/QN -type DFF DFF
add mapped point w_addr_reg[8]/q w_addr_reg_reg[8]/QN -type DFF DFF
add mapped point w_addr_reg[9]/q w_addr_reg_reg[9]/QN -type DFF DFF
add mapped point w_addr_reg[10]/q w_addr_reg_reg[10]/QN -type DFF DFF
add mapped point w_addr_reg[11]/q w_addr_reg_reg[11]/QN -type DFF DFF
add mapped point w_addr_reg[12]/q w_addr_reg_reg[12]/QN -type DFF DFF
add mapped point w_addr_reg[13]/q w_addr_reg_reg[13]/QN -type DFF DFF
add mapped point w_addr_reg[14]/q w_addr_reg_reg[14]/QN -type DFF DFF
add mapped point w_addr_reg[15]/q w_addr_reg_reg[15]/QN -type DFF DFF
add mapped point w_count_reg[0]/q w_count_reg_reg[0]/QN -type DFF DFF
add mapped point w_count_reg[1]/q w_count_reg_reg[1]/QN -type DFF DFF
add mapped point w_count_reg[2]/q w_count_reg_reg[2]/QN -type DFF DFF
add mapped point w_count_reg[3]/q w_count_reg_reg[3]/QN -type DFF DFF
add mapped point w_count_reg[4]/q w_count_reg_reg[4]/QN -type DFF DFF
add mapped point w_count_reg[5]/q w_count_reg_reg[5]/QN -type DFF DFF
add mapped point w_count_reg[6]/q w_count_reg_reg[6]/QN -type DFF DFF
add mapped point w_count_reg[7]/q w_count_reg_reg[7]/QN -type DFF DFF
add mapped point w_drop_reg/q w_drop_reg_reg/QN -type DFF DFF
add mapped point w_error_reg/q w_error_reg_reg/QN -type DFF DFF
add mapped point w_finish_hold/q w_finish_hold_reg/QN -type DFF DFF
add mapped point w_incr_reg/q w_incr_reg_reg/QN -type DFF DFF
add mapped point w_len_reg[0]/q w_len_reg_reg[0]/QN -type DFF DFF
add mapped point w_len_reg[1]/q w_len_reg_reg[1]/QN -type DFF DFF
add mapped point w_len_reg[2]/q w_len_reg_reg[2]/QN -type DFF DFF
add mapped point w_len_reg[3]/q w_len_reg_reg[3]/QN -type DFF DFF
add mapped point w_len_reg[4]/q w_len_reg_reg[4]/QN -type DFF DFF
add mapped point w_len_reg[5]/q w_len_reg_reg[5]/QN -type DFF DFF
add mapped point w_len_reg[6]/q w_len_reg_reg[6]/QN -type DFF DFF
add mapped point w_len_reg[7]/q w_len_reg_reg[7]/QN -type DFF DFF
add mapped point wdata_hold[0]/q wdata_hold_reg[0]/QN -type DFF DFF
add mapped point wdata_hold[1]/q wdata_hold_reg[1]/QN -type DFF DFF
add mapped point wdata_hold[2]/q wdata_hold_reg[2]/QN -type DFF DFF
add mapped point wdata_hold[3]/q wdata_hold_reg[3]/QN -type DFF DFF
add mapped point wdata_hold[4]/q wdata_hold_reg[4]/QN -type DFF DFF
add mapped point wdata_hold[5]/q wdata_hold_reg[5]/QN -type DFF DFF
add mapped point wdata_hold[6]/q wdata_hold_reg[6]/QN -type DFF DFF
add mapped point wdata_hold[7]/q wdata_hold_reg[7]/QN -type DFF DFF
add mapped point wdata_hold[8]/q wdata_hold_reg[8]/QN -type DFF DFF
add mapped point wdata_hold[9]/q wdata_hold_reg[9]/QN -type DFF DFF
add mapped point wdata_hold[10]/q wdata_hold_reg[10]/QN -type DFF DFF
add mapped point wdata_hold[11]/q wdata_hold_reg[11]/QN -type DFF DFF
add mapped point wdata_hold[12]/q wdata_hold_reg[12]/QN -type DFF DFF
add mapped point wdata_hold[13]/q wdata_hold_reg[13]/QN -type DFF DFF
add mapped point wdata_hold[14]/q wdata_hold_reg[14]/QN -type DFF DFF
add mapped point wdata_hold[15]/q wdata_hold_reg[15]/QN -type DFF DFF
add mapped point wdata_hold[16]/q wdata_hold_reg[16]/QN -type DFF DFF
add mapped point wdata_hold[17]/q wdata_hold_reg[17]/QN -type DFF DFF
add mapped point wdata_hold[18]/q wdata_hold_reg[18]/QN -type DFF DFF
add mapped point wdata_hold[19]/q wdata_hold_reg[19]/QN -type DFF DFF
add mapped point wdata_hold[20]/q wdata_hold_reg[20]/QN -type DFF DFF
add mapped point wdata_hold[21]/q wdata_hold_reg[21]/QN -type DFF DFF
add mapped point wdata_hold[22]/q wdata_hold_reg[22]/QN -type DFF DFF
add mapped point wdata_hold[23]/q wdata_hold_reg[23]/QN -type DFF DFF
add mapped point wdata_hold[24]/q wdata_hold_reg[24]/QN -type DFF DFF
add mapped point wdata_hold[25]/q wdata_hold_reg[25]/QN -type DFF DFF
add mapped point wdata_hold[26]/q wdata_hold_reg[26]/QN -type DFF DFF
add mapped point wdata_hold[27]/q wdata_hold_reg[27]/QN -type DFF DFF
add mapped point wdata_hold[28]/q wdata_hold_reg[28]/QN -type DFF DFF
add mapped point wdata_hold[29]/q wdata_hold_reg[29]/QN -type DFF DFF
add mapped point wdata_hold[30]/q wdata_hold_reg[30]/QN -type DFF DFF
add mapped point wdata_hold[31]/q wdata_hold_reg[31]/QN -type DFF DFF
add mapped point wstrb_hold[0]/q wstrb_hold_reg[0]/QN -type DFF DFF
add mapped point wstrb_hold[1]/q wstrb_hold_reg[1]/QN -type DFF DFF
add mapped point wstrb_hold[2]/q wstrb_hold_reg[2]/QN -type DFF DFF
add mapped point wstrb_hold[3]/q wstrb_hold_reg[3]/QN -type DFF DFF



//Black Boxes
add mapped point u_mem/G_SRAM_BANK[0].u_sram u_mem/G_SRAM_BANK[0].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[1].u_sram u_mem/G_SRAM_BANK[1].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[2].u_sram u_mem/G_SRAM_BANK[2].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[3].u_sram u_mem/G_SRAM_BANK[3].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[4].u_sram u_mem/G_SRAM_BANK[4].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[5].u_sram u_mem/G_SRAM_BANK[5].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[6].u_sram u_mem/G_SRAM_BANK[6].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[7].u_sram u_mem/G_SRAM_BANK[7].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[8].u_sram u_mem/G_SRAM_BANK[8].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[9].u_sram u_mem/G_SRAM_BANK[9].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[10].u_sram u_mem/G_SRAM_BANK[10].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[11].u_sram u_mem/G_SRAM_BANK[11].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[12].u_sram u_mem/G_SRAM_BANK[12].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[13].u_sram u_mem/G_SRAM_BANK[13].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[14].u_sram u_mem/G_SRAM_BANK[14].u_sram -type BBOX BBOX
add mapped point u_mem/G_SRAM_BANK[15].u_sram u_mem/G_SRAM_BANK[15].u_sram -type BBOX BBOX



//Empty Modules as Blackboxes
