
//input ports
add mapped point iclk iclk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point iA[31] iA[31] -type PI PI
add mapped point iA[30] iA[30] -type PI PI
add mapped point iA[29] iA[29] -type PI PI
add mapped point iA[28] iA[28] -type PI PI
add mapped point iA[27] iA[27] -type PI PI
add mapped point iA[26] iA[26] -type PI PI
add mapped point iA[25] iA[25] -type PI PI
add mapped point iA[24] iA[24] -type PI PI
add mapped point iA[23] iA[23] -type PI PI
add mapped point iA[22] iA[22] -type PI PI
add mapped point iA[21] iA[21] -type PI PI
add mapped point iA[20] iA[20] -type PI PI
add mapped point iA[19] iA[19] -type PI PI
add mapped point iA[18] iA[18] -type PI PI
add mapped point iA[17] iA[17] -type PI PI
add mapped point iA[16] iA[16] -type PI PI
add mapped point iA[15] iA[15] -type PI PI
add mapped point iA[14] iA[14] -type PI PI
add mapped point iA[13] iA[13] -type PI PI
add mapped point iA[12] iA[12] -type PI PI
add mapped point iA[11] iA[11] -type PI PI
add mapped point iA[10] iA[10] -type PI PI
add mapped point iA[9] iA[9] -type PI PI
add mapped point iA[8] iA[8] -type PI PI
add mapped point iA[7] iA[7] -type PI PI
add mapped point iA[6] iA[6] -type PI PI
add mapped point iA[5] iA[5] -type PI PI
add mapped point iA[4] iA[4] -type PI PI
add mapped point iA[3] iA[3] -type PI PI
add mapped point iA[2] iA[2] -type PI PI
add mapped point iA[1] iA[1] -type PI PI
add mapped point iA[0] iA[0] -type PI PI
add mapped point iB[31] iB[31] -type PI PI
add mapped point iB[30] iB[30] -type PI PI
add mapped point iB[29] iB[29] -type PI PI
add mapped point iB[28] iB[28] -type PI PI
add mapped point iB[27] iB[27] -type PI PI
add mapped point iB[26] iB[26] -type PI PI
add mapped point iB[25] iB[25] -type PI PI
add mapped point iB[24] iB[24] -type PI PI
add mapped point iB[23] iB[23] -type PI PI
add mapped point iB[22] iB[22] -type PI PI
add mapped point iB[21] iB[21] -type PI PI
add mapped point iB[20] iB[20] -type PI PI
add mapped point iB[19] iB[19] -type PI PI
add mapped point iB[18] iB[18] -type PI PI
add mapped point iB[17] iB[17] -type PI PI
add mapped point iB[16] iB[16] -type PI PI
add mapped point iB[15] iB[15] -type PI PI
add mapped point iB[14] iB[14] -type PI PI
add mapped point iB[13] iB[13] -type PI PI
add mapped point iB[12] iB[12] -type PI PI
add mapped point iB[11] iB[11] -type PI PI
add mapped point iB[10] iB[10] -type PI PI
add mapped point iB[9] iB[9] -type PI PI
add mapped point iB[8] iB[8] -type PI PI
add mapped point iB[7] iB[7] -type PI PI
add mapped point iB[6] iB[6] -type PI PI
add mapped point iB[5] iB[5] -type PI PI
add mapped point iB[4] iB[4] -type PI PI
add mapped point iB[3] iB[3] -type PI PI
add mapped point iB[2] iB[2] -type PI PI
add mapped point iB[1] iB[1] -type PI PI
add mapped point iB[0] iB[0] -type PI PI

//output ports
add mapped point oP[63] oP[63] -type PO PO
add mapped point oP[62] oP[62] -type PO PO
add mapped point oP[61] oP[61] -type PO PO
add mapped point oP[60] oP[60] -type PO PO
add mapped point oP[59] oP[59] -type PO PO
add mapped point oP[58] oP[58] -type PO PO
add mapped point oP[57] oP[57] -type PO PO
add mapped point oP[56] oP[56] -type PO PO
add mapped point oP[55] oP[55] -type PO PO
add mapped point oP[54] oP[54] -type PO PO
add mapped point oP[53] oP[53] -type PO PO
add mapped point oP[52] oP[52] -type PO PO
add mapped point oP[51] oP[51] -type PO PO
add mapped point oP[50] oP[50] -type PO PO
add mapped point oP[49] oP[49] -type PO PO
add mapped point oP[48] oP[48] -type PO PO
add mapped point oP[47] oP[47] -type PO PO
add mapped point oP[46] oP[46] -type PO PO
add mapped point oP[45] oP[45] -type PO PO
add mapped point oP[44] oP[44] -type PO PO
add mapped point oP[43] oP[43] -type PO PO
add mapped point oP[42] oP[42] -type PO PO
add mapped point oP[41] oP[41] -type PO PO
add mapped point oP[40] oP[40] -type PO PO
add mapped point oP[39] oP[39] -type PO PO
add mapped point oP[38] oP[38] -type PO PO
add mapped point oP[37] oP[37] -type PO PO
add mapped point oP[36] oP[36] -type PO PO
add mapped point oP[35] oP[35] -type PO PO
add mapped point oP[34] oP[34] -type PO PO
add mapped point oP[33] oP[33] -type PO PO
add mapped point oP[32] oP[32] -type PO PO
add mapped point oP[31] oP[31] -type PO PO
add mapped point oP[30] oP[30] -type PO PO
add mapped point oP[29] oP[29] -type PO PO
add mapped point oP[28] oP[28] -type PO PO
add mapped point oP[27] oP[27] -type PO PO
add mapped point oP[26] oP[26] -type PO PO
add mapped point oP[25] oP[25] -type PO PO
add mapped point oP[24] oP[24] -type PO PO
add mapped point oP[23] oP[23] -type PO PO
add mapped point oP[22] oP[22] -type PO PO
add mapped point oP[21] oP[21] -type PO PO
add mapped point oP[20] oP[20] -type PO PO
add mapped point oP[19] oP[19] -type PO PO
add mapped point oP[18] oP[18] -type PO PO
add mapped point oP[17] oP[17] -type PO PO
add mapped point oP[16] oP[16] -type PO PO
add mapped point oP[15] oP[15] -type PO PO
add mapped point oP[14] oP[14] -type PO PO
add mapped point oP[13] oP[13] -type PO PO
add mapped point oP[12] oP[12] -type PO PO
add mapped point oP[11] oP[11] -type PO PO
add mapped point oP[10] oP[10] -type PO PO
add mapped point oP[9] oP[9] -type PO PO
add mapped point oP[8] oP[8] -type PO PO
add mapped point oP[7] oP[7] -type PO PO
add mapped point oP[6] oP[6] -type PO PO
add mapped point oP[5] oP[5] -type PO PO
add mapped point oP[4] oP[4] -type PO PO
add mapped point oP[3] oP[3] -type PO PO
add mapped point oP[2] oP[2] -type PO PO
add mapped point oP[1] oP[1] -type PO PO
add mapped point oP[0] oP[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point oP[63]/q oP_reg[63]/QN -type DFF DFF
add mapped point oP[62]/q oP_reg[62]/QN -type DFF DFF
add mapped point oP[60]/q oP_reg[60]/QN -type DFF DFF
add mapped point oP[56]/q oP_reg[56]/QN -type DFF DFF
add mapped point oP[48]/q oP_reg[48]/QN -type DFF DFF
add mapped point oP[32]/q oP_reg[32]/QN -type DFF DFF
add mapped point oP[0]/q oP_reg[0]/QN -type DFF DFF
add mapped point oP[31]/q oP_reg[31]/QN -type DFF DFF
add mapped point oP[47]/q oP_reg[47]/QN -type DFF DFF
add mapped point oP[30]/q oP_reg[30]/QN -type DFF DFF
add mapped point oP[29]/q oP_reg[29]/QN -type DFF DFF
add mapped point oP[55]/q oP_reg[55]/QN -type DFF DFF
add mapped point oP[46]/q oP_reg[46]/QN -type DFF DFF
add mapped point oP[28]/q oP_reg[28]/QN -type DFF DFF
add mapped point oP[27]/q oP_reg[27]/QN -type DFF DFF
add mapped point oP[45]/q oP_reg[45]/QN -type DFF DFF
add mapped point oP[26]/q oP_reg[26]/QN -type DFF DFF
add mapped point oP[25]/q oP_reg[25]/QN -type DFF DFF
add mapped point oP[59]/q oP_reg[59]/QN -type DFF DFF
add mapped point oP[54]/q oP_reg[54]/QN -type DFF DFF
add mapped point oP[44]/q oP_reg[44]/QN -type DFF DFF
add mapped point oP[24]/q oP_reg[24]/QN -type DFF DFF
add mapped point oP[23]/q oP_reg[23]/QN -type DFF DFF
add mapped point oP[43]/q oP_reg[43]/QN -type DFF DFF
add mapped point oP[22]/q oP_reg[22]/QN -type DFF DFF
add mapped point oP[21]/q oP_reg[21]/QN -type DFF DFF
add mapped point oP[53]/q oP_reg[53]/QN -type DFF DFF
add mapped point oP[42]/q oP_reg[42]/QN -type DFF DFF
add mapped point oP[20]/q oP_reg[20]/QN -type DFF DFF
add mapped point oP[19]/q oP_reg[19]/QN -type DFF DFF
add mapped point oP[41]/q oP_reg[41]/QN -type DFF DFF
add mapped point oP[18]/q oP_reg[18]/QN -type DFF DFF
add mapped point oP[17]/q oP_reg[17]/QN -type DFF DFF
add mapped point oP[61]/q oP_reg[61]/QN -type DFF DFF
add mapped point oP[58]/q oP_reg[58]/QN -type DFF DFF
add mapped point oP[52]/q oP_reg[52]/QN -type DFF DFF
add mapped point oP[40]/q oP_reg[40]/QN -type DFF DFF
add mapped point oP[16]/q oP_reg[16]/QN -type DFF DFF
add mapped point oP[15]/q oP_reg[15]/QN -type DFF DFF
add mapped point oP[39]/q oP_reg[39]/QN -type DFF DFF
add mapped point oP[14]/q oP_reg[14]/QN -type DFF DFF
add mapped point oP[13]/q oP_reg[13]/QN -type DFF DFF
add mapped point oP[51]/q oP_reg[51]/QN -type DFF DFF
add mapped point oP[38]/q oP_reg[38]/QN -type DFF DFF
add mapped point oP[12]/q oP_reg[12]/QN -type DFF DFF
add mapped point oP[11]/q oP_reg[11]/QN -type DFF DFF
add mapped point oP[37]/q oP_reg[37]/QN -type DFF DFF
add mapped point oP[10]/q oP_reg[10]/QN -type DFF DFF
add mapped point oP[9]/q oP_reg[9]/QN -type DFF DFF
add mapped point oP[57]/q oP_reg[57]/QN -type DFF DFF
add mapped point oP[50]/q oP_reg[50]/QN -type DFF DFF
add mapped point oP[36]/q oP_reg[36]/QN -type DFF DFF
add mapped point oP[8]/q oP_reg[8]/QN -type DFF DFF
add mapped point oP[7]/q oP_reg[7]/QN -type DFF DFF
add mapped point oP[35]/q oP_reg[35]/QN -type DFF DFF
add mapped point oP[6]/q oP_reg[6]/QN -type DFF DFF
add mapped point oP[5]/q oP_reg[5]/QN -type DFF DFF
add mapped point oP[49]/q oP_reg[49]/QN -type DFF DFF
add mapped point oP[34]/q oP_reg[34]/QN -type DFF DFF
add mapped point oP[4]/q oP_reg[4]/QN -type DFF DFF
add mapped point oP[3]/q oP_reg[3]/QN -type DFF DFF
add mapped point oP[33]/q oP_reg[33]/QN -type DFF DFF
add mapped point oP[2]/q oP_reg[2]/QN -type DFF DFF
add mapped point oP[1]/q oP_reg[1]/QN -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
