###############################################################
#  Generated by:      Cadence Innovus 23.14-s088_1
#  OS:                Linux x86_64(Host ID user1-EliteMini)
#  Generated on:      Wed Aug 12 00:27:38 2026
#  Design:            riscv_pipeline
#  Command:           saveFPlan ./outputs/riscv_pipeline_hierFP.fp
###############################################################

Version: 8

Head Box: 0.0000 0.0000 316.9440 316.0800
IO Box: 0.0000 0.0000 316.9440 316.0800
Core Box: 3.8880 3.8880 313.0560 312.1920
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: asap7sc7p5t 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 asap7sc7p5t 3.8880 3.8880 FS 1431 1 0.2160 0.0000
DefRow: ROW_1 asap7sc7p5t 3.8880 4.9680 N 1431 1 0.2160 0.0000
DefRow: ROW_2 asap7sc7p5t 3.8880 6.0480 FS 1431 1 0.2160 0.0000
DefRow: ROW_3 asap7sc7p5t 3.8880 7.1280 N 1431 1 0.2160 0.0000
DefRow: ROW_4 asap7sc7p5t 3.8880 8.2080 FS 1431 1 0.2160 0.0000
DefRow: ROW_5 asap7sc7p5t 3.8880 9.2880 N 1431 1 0.2160 0.0000
DefRow: ROW_6 asap7sc7p5t 3.8880 10.3680 FS 1431 1 0.2160 0.0000
DefRow: ROW_7 asap7sc7p5t 3.8880 11.4480 N 1431 1 0.2160 0.0000
DefRow: ROW_8 asap7sc7p5t 3.8880 12.5280 FS 1431 1 0.2160 0.0000
DefRow: ROW_9 asap7sc7p5t 3.8880 13.6080 N 1431 1 0.2160 0.0000
DefRow: ROW_10 asap7sc7p5t 3.8880 14.6880 FS 1431 1 0.2160 0.0000
DefRow: ROW_11 asap7sc7p5t 3.8880 15.7680 N 1431 1 0.2160 0.0000
DefRow: ROW_12 asap7sc7p5t 3.8880 16.8480 FS 1431 1 0.2160 0.0000
DefRow: ROW_13 asap7sc7p5t 3.8880 17.9280 N 1431 1 0.2160 0.0000
DefRow: ROW_14 asap7sc7p5t 3.8880 19.0080 FS 1431 1 0.2160 0.0000
DefRow: ROW_15 asap7sc7p5t 3.8880 20.0880 N 1431 1 0.2160 0.0000
DefRow: ROW_16 asap7sc7p5t 3.8880 21.1680 FS 1431 1 0.2160 0.0000
DefRow: ROW_17 asap7sc7p5t 3.8880 22.2480 N 1431 1 0.2160 0.0000
DefRow: ROW_18 asap7sc7p5t 3.8880 23.3280 FS 1431 1 0.2160 0.0000
DefRow: ROW_19 asap7sc7p5t 3.8880 24.4080 N 1431 1 0.2160 0.0000
DefRow: ROW_20 asap7sc7p5t 3.8880 25.4880 FS 1431 1 0.2160 0.0000
DefRow: ROW_21 asap7sc7p5t 3.8880 26.5680 N 1431 1 0.2160 0.0000
DefRow: ROW_22 asap7sc7p5t 3.8880 27.6480 FS 1431 1 0.2160 0.0000
DefRow: ROW_23 asap7sc7p5t 3.8880 28.7280 N 1431 1 0.2160 0.0000
DefRow: ROW_24 asap7sc7p5t 3.8880 29.8080 FS 1431 1 0.2160 0.0000
DefRow: ROW_25 asap7sc7p5t 3.8880 30.8880 N 1431 1 0.2160 0.0000
DefRow: ROW_26 asap7sc7p5t 3.8880 31.9680 FS 1431 1 0.2160 0.0000
DefRow: ROW_27 asap7sc7p5t 3.8880 33.0480 N 1431 1 0.2160 0.0000
DefRow: ROW_28 asap7sc7p5t 3.8880 34.1280 FS 1431 1 0.2160 0.0000
DefRow: ROW_29 asap7sc7p5t 3.8880 35.2080 N 1431 1 0.2160 0.0000
DefRow: ROW_30 asap7sc7p5t 3.8880 36.2880 FS 1431 1 0.2160 0.0000
DefRow: ROW_31 asap7sc7p5t 3.8880 37.3680 N 1431 1 0.2160 0.0000
DefRow: ROW_32 asap7sc7p5t 3.8880 38.4480 FS 1431 1 0.2160 0.0000
DefRow: ROW_33 asap7sc7p5t 3.8880 39.5280 N 1431 1 0.2160 0.0000
DefRow: ROW_34 asap7sc7p5t 3.8880 40.6080 FS 1431 1 0.2160 0.0000
DefRow: ROW_35 asap7sc7p5t 3.8880 41.6880 N 1431 1 0.2160 0.0000
DefRow: ROW_36 asap7sc7p5t 3.8880 42.7680 FS 1431 1 0.2160 0.0000
DefRow: ROW_37 asap7sc7p5t 3.8880 43.8480 N 1431 1 0.2160 0.0000
DefRow: ROW_38 asap7sc7p5t 3.8880 44.9280 FS 1431 1 0.2160 0.0000
DefRow: ROW_39 asap7sc7p5t 3.8880 46.0080 N 1431 1 0.2160 0.0000
DefRow: ROW_40 asap7sc7p5t 3.8880 47.0880 FS 1431 1 0.2160 0.0000
DefRow: ROW_41 asap7sc7p5t 3.8880 48.1680 N 1431 1 0.2160 0.0000
DefRow: ROW_42 asap7sc7p5t 3.8880 49.2480 FS 1431 1 0.2160 0.0000
DefRow: ROW_43 asap7sc7p5t 3.8880 50.3280 N 1431 1 0.2160 0.0000
DefRow: ROW_44 asap7sc7p5t 3.8880 51.4080 FS 1431 1 0.2160 0.0000
DefRow: ROW_45 asap7sc7p5t 3.8880 52.4880 N 1431 1 0.2160 0.0000
DefRow: ROW_46 asap7sc7p5t 3.8880 53.5680 FS 1431 1 0.2160 0.0000
DefRow: ROW_47 asap7sc7p5t 3.8880 54.6480 N 1431 1 0.2160 0.0000
DefRow: ROW_48 asap7sc7p5t 3.8880 55.7280 FS 1431 1 0.2160 0.0000
DefRow: ROW_49 asap7sc7p5t 3.8880 56.8080 N 1431 1 0.2160 0.0000
DefRow: ROW_50 asap7sc7p5t 3.8880 57.8880 FS 1431 1 0.2160 0.0000
DefRow: ROW_51 asap7sc7p5t 3.8880 58.9680 N 1431 1 0.2160 0.0000
DefRow: ROW_52 asap7sc7p5t 3.8880 60.0480 FS 1431 1 0.2160 0.0000
DefRow: ROW_53 asap7sc7p5t 3.8880 61.1280 N 1431 1 0.2160 0.0000
DefRow: ROW_54 asap7sc7p5t 3.8880 62.2080 FS 1431 1 0.2160 0.0000
DefRow: ROW_55 asap7sc7p5t 3.8880 63.2880 N 1431 1 0.2160 0.0000
DefRow: ROW_56 asap7sc7p5t 3.8880 64.3680 FS 1431 1 0.2160 0.0000
DefRow: ROW_57 asap7sc7p5t 3.8880 65.4480 N 1431 1 0.2160 0.0000
DefRow: ROW_58 asap7sc7p5t 3.8880 66.5280 FS 1431 1 0.2160 0.0000
DefRow: ROW_59 asap7sc7p5t 3.8880 67.6080 N 1431 1 0.2160 0.0000
DefRow: ROW_60 asap7sc7p5t 3.8880 68.6880 FS 1431 1 0.2160 0.0000
DefRow: ROW_61 asap7sc7p5t 3.8880 69.7680 N 1431 1 0.2160 0.0000
DefRow: ROW_62 asap7sc7p5t 3.8880 70.8480 FS 1431 1 0.2160 0.0000
DefRow: ROW_63 asap7sc7p5t 3.8880 71.9280 N 1431 1 0.2160 0.0000
DefRow: ROW_64 asap7sc7p5t 3.8880 73.0080 FS 1431 1 0.2160 0.0000
DefRow: ROW_65 asap7sc7p5t 3.8880 74.0880 N 1431 1 0.2160 0.0000
DefRow: ROW_66 asap7sc7p5t 3.8880 75.1680 FS 1431 1 0.2160 0.0000
DefRow: ROW_67 asap7sc7p5t 3.8880 76.2480 N 1431 1 0.2160 0.0000
DefRow: ROW_68 asap7sc7p5t 3.8880 77.3280 FS 1431 1 0.2160 0.0000
DefRow: ROW_69 asap7sc7p5t 3.8880 78.4080 N 1431 1 0.2160 0.0000
DefRow: ROW_70 asap7sc7p5t 3.8880 79.4880 FS 1431 1 0.2160 0.0000
DefRow: ROW_71 asap7sc7p5t 3.8880 80.5680 N 1431 1 0.2160 0.0000
DefRow: ROW_72 asap7sc7p5t 3.8880 81.6480 FS 1431 1 0.2160 0.0000
DefRow: ROW_73 asap7sc7p5t 3.8880 82.7280 N 1431 1 0.2160 0.0000
DefRow: ROW_74 asap7sc7p5t 3.8880 83.8080 FS 1431 1 0.2160 0.0000
DefRow: ROW_75 asap7sc7p5t 3.8880 84.8880 N 1431 1 0.2160 0.0000
DefRow: ROW_76 asap7sc7p5t 3.8880 85.9680 FS 1431 1 0.2160 0.0000
DefRow: ROW_77 asap7sc7p5t 3.8880 87.0480 N 1431 1 0.2160 0.0000
DefRow: ROW_78 asap7sc7p5t 3.8880 88.1280 FS 1431 1 0.2160 0.0000
DefRow: ROW_79 asap7sc7p5t 3.8880 89.2080 N 1431 1 0.2160 0.0000
DefRow: ROW_80 asap7sc7p5t 3.8880 90.2880 FS 1431 1 0.2160 0.0000
DefRow: ROW_81 asap7sc7p5t 3.8880 91.3680 N 1431 1 0.2160 0.0000
DefRow: ROW_82 asap7sc7p5t 3.8880 92.4480 FS 1431 1 0.2160 0.0000
DefRow: ROW_83 asap7sc7p5t 3.8880 93.5280 N 1431 1 0.2160 0.0000
DefRow: ROW_84 asap7sc7p5t 3.8880 94.6080 FS 1431 1 0.2160 0.0000
DefRow: ROW_85 asap7sc7p5t 3.8880 95.6880 N 1431 1 0.2160 0.0000
DefRow: ROW_86 asap7sc7p5t 3.8880 96.7680 FS 1431 1 0.2160 0.0000
DefRow: ROW_87 asap7sc7p5t 3.8880 97.8480 N 1431 1 0.2160 0.0000
DefRow: ROW_88 asap7sc7p5t 3.8880 98.9280 FS 1431 1 0.2160 0.0000
DefRow: ROW_89 asap7sc7p5t 3.8880 100.0080 N 1431 1 0.2160 0.0000
DefRow: ROW_90 asap7sc7p5t 3.8880 101.0880 FS 1431 1 0.2160 0.0000
DefRow: ROW_91 asap7sc7p5t 3.8880 102.1680 N 1431 1 0.2160 0.0000
DefRow: ROW_92 asap7sc7p5t 3.8880 103.2480 FS 1431 1 0.2160 0.0000
DefRow: ROW_93 asap7sc7p5t 3.8880 104.3280 N 1431 1 0.2160 0.0000
DefRow: ROW_94 asap7sc7p5t 3.8880 105.4080 FS 1431 1 0.2160 0.0000
DefRow: ROW_95 asap7sc7p5t 3.8880 106.4880 N 1431 1 0.2160 0.0000
DefRow: ROW_96 asap7sc7p5t 3.8880 107.5680 FS 1431 1 0.2160 0.0000
DefRow: ROW_97 asap7sc7p5t 3.8880 108.6480 N 1431 1 0.2160 0.0000
DefRow: ROW_98 asap7sc7p5t 3.8880 109.7280 FS 1431 1 0.2160 0.0000
DefRow: ROW_99 asap7sc7p5t 3.8880 110.8080 N 1431 1 0.2160 0.0000
DefRow: ROW_100 asap7sc7p5t 3.8880 111.8880 FS 1431 1 0.2160 0.0000
DefRow: ROW_101 asap7sc7p5t 3.8880 112.9680 N 1431 1 0.2160 0.0000
DefRow: ROW_102 asap7sc7p5t 3.8880 114.0480 FS 1431 1 0.2160 0.0000
DefRow: ROW_103 asap7sc7p5t 3.8880 115.1280 N 1431 1 0.2160 0.0000
DefRow: ROW_104 asap7sc7p5t 3.8880 116.2080 FS 1431 1 0.2160 0.0000
DefRow: ROW_105 asap7sc7p5t 3.8880 117.2880 N 1431 1 0.2160 0.0000
DefRow: ROW_106 asap7sc7p5t 3.8880 118.3680 FS 1431 1 0.2160 0.0000
DefRow: ROW_107 asap7sc7p5t 3.8880 119.4480 N 1431 1 0.2160 0.0000
DefRow: ROW_108 asap7sc7p5t 3.8880 120.5280 FS 1431 1 0.2160 0.0000
DefRow: ROW_109 asap7sc7p5t 3.8880 121.6080 N 1431 1 0.2160 0.0000
DefRow: ROW_110 asap7sc7p5t 3.8880 122.6880 FS 1431 1 0.2160 0.0000
DefRow: ROW_111 asap7sc7p5t 3.8880 123.7680 N 1431 1 0.2160 0.0000
DefRow: ROW_112 asap7sc7p5t 3.8880 124.8480 FS 1431 1 0.2160 0.0000
DefRow: ROW_113 asap7sc7p5t 3.8880 125.9280 N 1431 1 0.2160 0.0000
DefRow: ROW_114 asap7sc7p5t 3.8880 127.0080 FS 1431 1 0.2160 0.0000
DefRow: ROW_115 asap7sc7p5t 3.8880 128.0880 N 1431 1 0.2160 0.0000
DefRow: ROW_116 asap7sc7p5t 3.8880 129.1680 FS 1431 1 0.2160 0.0000
DefRow: ROW_117 asap7sc7p5t 3.8880 130.2480 N 1431 1 0.2160 0.0000
DefRow: ROW_118 asap7sc7p5t 3.8880 131.3280 FS 1431 1 0.2160 0.0000
DefRow: ROW_119 asap7sc7p5t 3.8880 132.4080 N 1431 1 0.2160 0.0000
DefRow: ROW_120 asap7sc7p5t 3.8880 133.4880 FS 1431 1 0.2160 0.0000
DefRow: ROW_121 asap7sc7p5t 3.8880 134.5680 N 1431 1 0.2160 0.0000
DefRow: ROW_122 asap7sc7p5t 3.8880 135.6480 FS 1431 1 0.2160 0.0000
DefRow: ROW_123 asap7sc7p5t 3.8880 136.7280 N 1431 1 0.2160 0.0000
DefRow: ROW_124 asap7sc7p5t 3.8880 137.8080 FS 1431 1 0.2160 0.0000
DefRow: ROW_125 asap7sc7p5t 3.8880 138.8880 N 1431 1 0.2160 0.0000
DefRow: ROW_126 asap7sc7p5t 3.8880 139.9680 FS 1431 1 0.2160 0.0000
DefRow: ROW_127 asap7sc7p5t 3.8880 141.0480 N 1431 1 0.2160 0.0000
DefRow: ROW_128 asap7sc7p5t 3.8880 142.1280 FS 1431 1 0.2160 0.0000
DefRow: ROW_129 asap7sc7p5t 3.8880 143.2080 N 1431 1 0.2160 0.0000
DefRow: ROW_130 asap7sc7p5t 3.8880 144.2880 FS 1431 1 0.2160 0.0000
DefRow: ROW_131 asap7sc7p5t 3.8880 145.3680 N 1431 1 0.2160 0.0000
DefRow: ROW_132 asap7sc7p5t 3.8880 146.4480 FS 1431 1 0.2160 0.0000
DefRow: ROW_133 asap7sc7p5t 3.8880 147.5280 N 1431 1 0.2160 0.0000
DefRow: ROW_134 asap7sc7p5t 3.8880 148.6080 FS 1431 1 0.2160 0.0000
DefRow: ROW_135 asap7sc7p5t 3.8880 149.6880 N 1431 1 0.2160 0.0000
DefRow: ROW_136 asap7sc7p5t 3.8880 150.7680 FS 1431 1 0.2160 0.0000
DefRow: ROW_137 asap7sc7p5t 3.8880 151.8480 N 1431 1 0.2160 0.0000
DefRow: ROW_138 asap7sc7p5t 3.8880 152.9280 FS 1431 1 0.2160 0.0000
DefRow: ROW_139 asap7sc7p5t 3.8880 154.0080 N 1431 1 0.2160 0.0000
DefRow: ROW_140 asap7sc7p5t 3.8880 155.0880 FS 1431 1 0.2160 0.0000
DefRow: ROW_141 asap7sc7p5t 3.8880 156.1680 N 1431 1 0.2160 0.0000
DefRow: ROW_142 asap7sc7p5t 3.8880 157.2480 FS 1431 1 0.2160 0.0000
DefRow: ROW_143 asap7sc7p5t 3.8880 158.3280 N 1431 1 0.2160 0.0000
DefRow: ROW_144 asap7sc7p5t 3.8880 159.4080 FS 1431 1 0.2160 0.0000
DefRow: ROW_145 asap7sc7p5t 3.8880 160.4880 N 1431 1 0.2160 0.0000
DefRow: ROW_146 asap7sc7p5t 3.8880 161.5680 FS 1431 1 0.2160 0.0000
DefRow: ROW_147 asap7sc7p5t 3.8880 162.6480 N 1431 1 0.2160 0.0000
DefRow: ROW_148 asap7sc7p5t 3.8880 163.7280 FS 1431 1 0.2160 0.0000
DefRow: ROW_149 asap7sc7p5t 3.8880 164.8080 N 1431 1 0.2160 0.0000
DefRow: ROW_150 asap7sc7p5t 3.8880 165.8880 FS 1431 1 0.2160 0.0000
DefRow: ROW_151 asap7sc7p5t 3.8880 166.9680 N 1431 1 0.2160 0.0000
DefRow: ROW_152 asap7sc7p5t 3.8880 168.0480 FS 1431 1 0.2160 0.0000
DefRow: ROW_153 asap7sc7p5t 3.8880 169.1280 N 1431 1 0.2160 0.0000
DefRow: ROW_154 asap7sc7p5t 3.8880 170.2080 FS 1431 1 0.2160 0.0000
DefRow: ROW_155 asap7sc7p5t 3.8880 171.2880 N 1431 1 0.2160 0.0000
DefRow: ROW_156 asap7sc7p5t 3.8880 172.3680 FS 1431 1 0.2160 0.0000
DefRow: ROW_157 asap7sc7p5t 3.8880 173.4480 N 1431 1 0.2160 0.0000
DefRow: ROW_158 asap7sc7p5t 3.8880 174.5280 FS 1431 1 0.2160 0.0000
DefRow: ROW_159 asap7sc7p5t 3.8880 175.6080 N 1431 1 0.2160 0.0000
DefRow: ROW_160 asap7sc7p5t 3.8880 176.6880 FS 1431 1 0.2160 0.0000
DefRow: ROW_161 asap7sc7p5t 3.8880 177.7680 N 1431 1 0.2160 0.0000
DefRow: ROW_162 asap7sc7p5t 3.8880 178.8480 FS 1431 1 0.2160 0.0000
DefRow: ROW_163 asap7sc7p5t 3.8880 179.9280 N 1431 1 0.2160 0.0000
DefRow: ROW_164 asap7sc7p5t 3.8880 181.0080 FS 1431 1 0.2160 0.0000
DefRow: ROW_165 asap7sc7p5t 3.8880 182.0880 N 1431 1 0.2160 0.0000
DefRow: ROW_166 asap7sc7p5t 3.8880 183.1680 FS 1431 1 0.2160 0.0000
DefRow: ROW_167 asap7sc7p5t 3.8880 184.2480 N 1431 1 0.2160 0.0000
DefRow: ROW_168 asap7sc7p5t 3.8880 185.3280 FS 1431 1 0.2160 0.0000
DefRow: ROW_169 asap7sc7p5t 3.8880 186.4080 N 1431 1 0.2160 0.0000
DefRow: ROW_170 asap7sc7p5t 3.8880 187.4880 FS 1431 1 0.2160 0.0000
DefRow: ROW_171 asap7sc7p5t 3.8880 188.5680 N 1431 1 0.2160 0.0000
DefRow: ROW_172 asap7sc7p5t 3.8880 189.6480 FS 1431 1 0.2160 0.0000
DefRow: ROW_173 asap7sc7p5t 3.8880 190.7280 N 1431 1 0.2160 0.0000
DefRow: ROW_174 asap7sc7p5t 3.8880 191.8080 FS 1431 1 0.2160 0.0000
DefRow: ROW_175 asap7sc7p5t 3.8880 192.8880 N 1431 1 0.2160 0.0000
DefRow: ROW_176 asap7sc7p5t 3.8880 193.9680 FS 1431 1 0.2160 0.0000
DefRow: ROW_177 asap7sc7p5t 3.8880 195.0480 N 1431 1 0.2160 0.0000
DefRow: ROW_178 asap7sc7p5t 3.8880 196.1280 FS 1431 1 0.2160 0.0000
DefRow: ROW_179 asap7sc7p5t 3.8880 197.2080 N 1431 1 0.2160 0.0000
DefRow: ROW_180 asap7sc7p5t 3.8880 198.2880 FS 1431 1 0.2160 0.0000
DefRow: ROW_181 asap7sc7p5t 3.8880 199.3680 N 1431 1 0.2160 0.0000
DefRow: ROW_182 asap7sc7p5t 3.8880 200.4480 FS 1431 1 0.2160 0.0000
DefRow: ROW_183 asap7sc7p5t 3.8880 201.5280 N 1431 1 0.2160 0.0000
DefRow: ROW_184 asap7sc7p5t 3.8880 202.6080 FS 1431 1 0.2160 0.0000
DefRow: ROW_185 asap7sc7p5t 3.8880 203.6880 N 1431 1 0.2160 0.0000
DefRow: ROW_186 asap7sc7p5t 3.8880 204.7680 FS 1431 1 0.2160 0.0000
DefRow: ROW_187 asap7sc7p5t 3.8880 205.8480 N 1431 1 0.2160 0.0000
DefRow: ROW_188 asap7sc7p5t 3.8880 206.9280 FS 1431 1 0.2160 0.0000
DefRow: ROW_189 asap7sc7p5t 3.8880 208.0080 N 1431 1 0.2160 0.0000
DefRow: ROW_190 asap7sc7p5t 3.8880 209.0880 FS 1431 1 0.2160 0.0000
DefRow: ROW_191 asap7sc7p5t 3.8880 210.1680 N 1431 1 0.2160 0.0000
DefRow: ROW_192 asap7sc7p5t 3.8880 211.2480 FS 1431 1 0.2160 0.0000
DefRow: ROW_193 asap7sc7p5t 3.8880 212.3280 N 1431 1 0.2160 0.0000
DefRow: ROW_194 asap7sc7p5t 3.8880 213.4080 FS 1431 1 0.2160 0.0000
DefRow: ROW_195 asap7sc7p5t 3.8880 214.4880 N 1431 1 0.2160 0.0000
DefRow: ROW_196 asap7sc7p5t 3.8880 215.5680 FS 1431 1 0.2160 0.0000
DefRow: ROW_197 asap7sc7p5t 3.8880 216.6480 N 1431 1 0.2160 0.0000
DefRow: ROW_198 asap7sc7p5t 3.8880 217.7280 FS 1431 1 0.2160 0.0000
DefRow: ROW_199 asap7sc7p5t 3.8880 218.8080 N 1431 1 0.2160 0.0000
DefRow: ROW_200 asap7sc7p5t 3.8880 219.8880 FS 1431 1 0.2160 0.0000
DefRow: ROW_201 asap7sc7p5t 3.8880 220.9680 N 1431 1 0.2160 0.0000
DefRow: ROW_202 asap7sc7p5t 3.8880 222.0480 FS 1431 1 0.2160 0.0000
DefRow: ROW_203 asap7sc7p5t 3.8880 223.1280 N 1431 1 0.2160 0.0000
DefRow: ROW_204 asap7sc7p5t 3.8880 224.2080 FS 1431 1 0.2160 0.0000
DefRow: ROW_205 asap7sc7p5t 3.8880 225.2880 N 1431 1 0.2160 0.0000
DefRow: ROW_206 asap7sc7p5t 3.8880 226.3680 FS 1431 1 0.2160 0.0000
DefRow: ROW_207 asap7sc7p5t 3.8880 227.4480 N 1431 1 0.2160 0.0000
DefRow: ROW_208 asap7sc7p5t 3.8880 228.5280 FS 1431 1 0.2160 0.0000
DefRow: ROW_209 asap7sc7p5t 3.8880 229.6080 N 1431 1 0.2160 0.0000
DefRow: ROW_210 asap7sc7p5t 3.8880 230.6880 FS 1431 1 0.2160 0.0000
DefRow: ROW_211 asap7sc7p5t 3.8880 231.7680 N 1431 1 0.2160 0.0000
DefRow: ROW_212 asap7sc7p5t 3.8880 232.8480 FS 1431 1 0.2160 0.0000
DefRow: ROW_213 asap7sc7p5t 3.8880 233.9280 N 1431 1 0.2160 0.0000
DefRow: ROW_214 asap7sc7p5t 3.8880 235.0080 FS 1431 1 0.2160 0.0000
DefRow: ROW_215 asap7sc7p5t 3.8880 236.0880 N 1431 1 0.2160 0.0000
DefRow: ROW_216 asap7sc7p5t 3.8880 237.1680 FS 1431 1 0.2160 0.0000
DefRow: ROW_217 asap7sc7p5t 3.8880 238.2480 N 1431 1 0.2160 0.0000
DefRow: ROW_218 asap7sc7p5t 3.8880 239.3280 FS 1431 1 0.2160 0.0000
DefRow: ROW_219 asap7sc7p5t 3.8880 240.4080 N 1431 1 0.2160 0.0000
DefRow: ROW_220 asap7sc7p5t 3.8880 241.4880 FS 1431 1 0.2160 0.0000
DefRow: ROW_221 asap7sc7p5t 3.8880 242.5680 N 1431 1 0.2160 0.0000
DefRow: ROW_222 asap7sc7p5t 3.8880 243.6480 FS 1431 1 0.2160 0.0000
DefRow: ROW_223 asap7sc7p5t 3.8880 244.7280 N 1431 1 0.2160 0.0000
DefRow: ROW_224 asap7sc7p5t 3.8880 245.8080 FS 1431 1 0.2160 0.0000
DefRow: ROW_225 asap7sc7p5t 3.8880 246.8880 N 1431 1 0.2160 0.0000
DefRow: ROW_226 asap7sc7p5t 3.8880 247.9680 FS 1431 1 0.2160 0.0000
DefRow: ROW_227 asap7sc7p5t 3.8880 249.0480 N 1431 1 0.2160 0.0000
DefRow: ROW_228 asap7sc7p5t 3.8880 250.1280 FS 1431 1 0.2160 0.0000
DefRow: ROW_229 asap7sc7p5t 3.8880 251.2080 N 1431 1 0.2160 0.0000
DefRow: ROW_230 asap7sc7p5t 3.8880 252.2880 FS 1431 1 0.2160 0.0000
DefRow: ROW_231 asap7sc7p5t 3.8880 253.3680 N 1431 1 0.2160 0.0000
DefRow: ROW_232 asap7sc7p5t 3.8880 254.4480 FS 1431 1 0.2160 0.0000
DefRow: ROW_233 asap7sc7p5t 3.8880 255.5280 N 1431 1 0.2160 0.0000
DefRow: ROW_234 asap7sc7p5t 3.8880 256.6080 FS 1431 1 0.2160 0.0000
DefRow: ROW_235 asap7sc7p5t 3.8880 257.6880 N 1431 1 0.2160 0.0000
DefRow: ROW_236 asap7sc7p5t 3.8880 258.7680 FS 1431 1 0.2160 0.0000
DefRow: ROW_237 asap7sc7p5t 3.8880 259.8480 N 1431 1 0.2160 0.0000
DefRow: ROW_238 asap7sc7p5t 3.8880 260.9280 FS 1431 1 0.2160 0.0000
DefRow: ROW_239 asap7sc7p5t 3.8880 262.0080 N 1431 1 0.2160 0.0000
DefRow: ROW_240 asap7sc7p5t 3.8880 263.0880 FS 1431 1 0.2160 0.0000
DefRow: ROW_241 asap7sc7p5t 3.8880 264.1680 N 1431 1 0.2160 0.0000
DefRow: ROW_242 asap7sc7p5t 3.8880 265.2480 FS 1431 1 0.2160 0.0000
DefRow: ROW_243 asap7sc7p5t 3.8880 266.3280 N 1431 1 0.2160 0.0000
DefRow: ROW_244 asap7sc7p5t 3.8880 267.4080 FS 1431 1 0.2160 0.0000
DefRow: ROW_245 asap7sc7p5t 3.8880 268.4880 N 1431 1 0.2160 0.0000
DefRow: ROW_246 asap7sc7p5t 3.8880 269.5680 FS 1431 1 0.2160 0.0000
DefRow: ROW_247 asap7sc7p5t 3.8880 270.6480 N 1431 1 0.2160 0.0000
DefRow: ROW_248 asap7sc7p5t 3.8880 271.7280 FS 1431 1 0.2160 0.0000
DefRow: ROW_249 asap7sc7p5t 3.8880 272.8080 N 1431 1 0.2160 0.0000
DefRow: ROW_250 asap7sc7p5t 3.8880 273.8880 FS 1431 1 0.2160 0.0000
DefRow: ROW_251 asap7sc7p5t 3.8880 274.9680 N 1431 1 0.2160 0.0000
DefRow: ROW_252 asap7sc7p5t 3.8880 276.0480 FS 1431 1 0.2160 0.0000
DefRow: ROW_253 asap7sc7p5t 3.8880 277.1280 N 1431 1 0.2160 0.0000
DefRow: ROW_254 asap7sc7p5t 3.8880 278.2080 FS 1431 1 0.2160 0.0000
DefRow: ROW_255 asap7sc7p5t 3.8880 279.2880 N 1431 1 0.2160 0.0000
DefRow: ROW_256 asap7sc7p5t 3.8880 280.3680 FS 1431 1 0.2160 0.0000
DefRow: ROW_257 asap7sc7p5t 3.8880 281.4480 N 1431 1 0.2160 0.0000
DefRow: ROW_258 asap7sc7p5t 3.8880 282.5280 FS 1431 1 0.2160 0.0000
DefRow: ROW_259 asap7sc7p5t 3.8880 283.6080 N 1431 1 0.2160 0.0000
DefRow: ROW_260 asap7sc7p5t 3.8880 284.6880 FS 1431 1 0.2160 0.0000
DefRow: ROW_261 asap7sc7p5t 3.8880 285.7680 N 1431 1 0.2160 0.0000
DefRow: ROW_262 asap7sc7p5t 3.8880 286.8480 FS 1431 1 0.2160 0.0000
DefRow: ROW_263 asap7sc7p5t 3.8880 287.9280 N 1431 1 0.2160 0.0000
DefRow: ROW_264 asap7sc7p5t 3.8880 289.0080 FS 1431 1 0.2160 0.0000
DefRow: ROW_265 asap7sc7p5t 3.8880 290.0880 N 1431 1 0.2160 0.0000
DefRow: ROW_266 asap7sc7p5t 3.8880 291.1680 FS 1431 1 0.2160 0.0000
DefRow: ROW_267 asap7sc7p5t 3.8880 292.2480 N 1431 1 0.2160 0.0000
DefRow: ROW_268 asap7sc7p5t 3.8880 293.3280 FS 1431 1 0.2160 0.0000
DefRow: ROW_269 asap7sc7p5t 3.8880 294.4080 N 1431 1 0.2160 0.0000
DefRow: ROW_270 asap7sc7p5t 3.8880 295.4880 FS 1431 1 0.2160 0.0000
DefRow: ROW_271 asap7sc7p5t 3.8880 296.5680 N 1431 1 0.2160 0.0000
DefRow: ROW_272 asap7sc7p5t 3.8880 297.6480 FS 1431 1 0.2160 0.0000
DefRow: ROW_273 asap7sc7p5t 3.8880 298.7280 N 1431 1 0.2160 0.0000
DefRow: ROW_274 asap7sc7p5t 3.8880 299.8080 FS 1431 1 0.2160 0.0000
DefRow: ROW_275 asap7sc7p5t 3.8880 300.8880 N 1431 1 0.2160 0.0000
DefRow: ROW_276 asap7sc7p5t 3.8880 301.9680 FS 1431 1 0.2160 0.0000
DefRow: ROW_277 asap7sc7p5t 3.8880 303.0480 N 1431 1 0.2160 0.0000
DefRow: ROW_278 asap7sc7p5t 3.8880 304.1280 FS 1431 1 0.2160 0.0000
DefRow: ROW_279 asap7sc7p5t 3.8880 305.2080 N 1431 1 0.2160 0.0000
DefRow: ROW_280 asap7sc7p5t 3.8880 306.2880 FS 1431 1 0.2160 0.0000
DefRow: ROW_281 asap7sc7p5t 3.8880 307.3680 N 1431 1 0.2160 0.0000
DefRow: ROW_282 asap7sc7p5t 3.8880 308.4480 FS 1431 1 0.2160 0.0000
DefRow: ROW_283 asap7sc7p5t 3.8880 309.5280 N 1431 1 0.2160 0.0000
DefRow: ROW_284 asap7sc7p5t 3.8880 310.6080 FS 1431 1 0.2160 0.0000

###########################################################################################
#  <Tracks>                                                                               #
#     <Track dir="X|Y" start=1.2 number=1 space=1.2 layer_num=2 layer="1 2" >             #
#       <Attr first_color=1 is_same_color=1 width=1.2 rule="rule_name" is_rect_only=1 />  #
#     </Track>                                                                            #
#  </Tracks>                                                                              #
###########################################################################################
<Tracks>
  <Track dir="X" start=0.5040 number=879 space=0.3600 layer_num=1 layer=" 10 " >
  </Track>
  <Track dir="Y" start=8.4240 number=38 space=8.2800 layer_num=1 layer=" 10 " >
  </Track>
  <Track dir="Y" start=0.5280 number=822 space=0.3840 layer_num=1 layer=" 9 " >
  </Track>
  <Track dir="X" start=0.5040 number=879 space=0.3600 layer_num=1 layer=" 9 " >
  </Track>
  <Track dir="X" start=0.1440 number=1100 space=0.2880 layer_num=1 layer=" 8 " >
  </Track>
  <Track dir="Y" start=0.5280 number=822 space=0.3840 layer_num=1 layer=" 8 " >
  </Track>
  <Track dir="Y" start=0.1440 number=1097 space=0.2880 layer_num=1 layer=" 7 " >
  </Track>
  <Track dir="X" start=0.1440 number=1100 space=0.2880 layer_num=1 layer=" 7 " >
  </Track>
  <Track dir="X" start=0.2160 number=1467 space=0.2160 layer_num=1 layer=" 6 " >
  </Track>
  <Track dir="Y" start=0.1440 number=1097 space=0.2880 layer_num=1 layer=" 6 " >
  </Track>
  <Track dir="Y" start=0.2520 number=1645 space=0.1920 layer_num=1 layer=" 5 " >
  </Track>
  <Track dir="X" start=0.2160 number=1467 space=0.2160 layer_num=1 layer=" 5 " >
  </Track>
  <Track dir="X" start=0.1440 number=2200 space=0.1440 layer_num=1 layer=" 4 " >
  </Track>
  <Track dir="Y" start=0.2520 number=1645 space=0.1920 layer_num=1 layer=" 4 " >
  </Track>
  <Track dir="Y" start=0.1440 number=2194 space=0.1440 layer_num=1 layer=" 3 " >
  </Track>
  <Track dir="X" start=0.1440 number=2200 space=0.1440 layer_num=1 layer=" 3 " >
  </Track>
  <Track dir="X" start=0.1440 number=2200 space=0.1440 layer_num=1 layer=" 2 " >
  </Track>
  <Track dir="Y" start=0.8280 number=292 space=1.0800 layer_num=1 layer=" 2 " >
  </Track>
  <Track dir="Y" start=0.9720 number=292 space=1.0800 layer_num=1 layer=" 2 " >
  </Track>
  <Track dir="Y" start=1.1160 number=292 space=1.0800 layer_num=1 layer=" 2 " >
  </Track>
  <Track dir="Y" start=1.2600 number=292 space=1.0800 layer_num=1 layer=" 2 " >
  </Track>
  <Track dir="Y" start=1.4040 number=292 space=1.0800 layer_num=1 layer=" 2 " >
  </Track>
  <Track dir="Y" start=1.5480 number=292 space=1.0800 layer_num=1 layer=" 2 " >
  </Track>
  <Track dir="Y" start=0.6480 number=293 space=1.0800 layer_num=1 layer=" 2 " >
  </Track>
  <Track dir="Y" start=0.1440 number=2194 space=0.1440 layer_num=1 layer=" 1 " >
  </Track>
  <Track dir="X" start=0.1440 number=2200 space=0.1440 layer_num=1 layer=" 1 " >
  </Track>
</Tracks>

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 0.1440 221 1.4400
GCellGrid: X 0.0000 2 0.1440
GCellGrid: Y 314.0280 2 2.0520
GCellGrid: Y 0.8280 30 10.8000
GCellGrid: Y 0.0000 2 0.8280

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: VSS -gnd

#####################################################################################
# <PGNets>                                                                          #
#    <PGNet name="net_name">                                                        #
#       <HNet name="hnet_name">                                                     #
#          <Port hinst="hinst_name" name="port_name" direction="in|out|inout" />    #
#       </HNet>                                                                     #
#    </PGNet>                                                                       #
# </PGNets>                                                                         #
#####################################################################################

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################

###########################################################################
#  <macro_place_constraint>                                               #
#          ...                                                            #
#  </macro_place_constraint>                                              #
###########################################################################
<macro_place_constraint>
</macro_place_constraint>

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

###########################################################################
#  BlockRoutingHalo: <name> <space> <bottomLayer> <topLayer> <-lithoHalo> #
###########################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinSpacing layer=layerId spacing=val />                        #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val   #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val isMixedSignal=val >         #
#         <Net name="net_name" /> ...                                   #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <DefaultTechSite name="core" />                                   #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d spacing=val />   #
#         <LayerSpecialWireDepth  layer=<layerId>  depth=<depth />        #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge2 edgeMap=val />                                    #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr        #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val >                           #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="riscv_pipeline" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x3ff orient=R0>
	<PinLayer side="N" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
	<PinLayer side="W" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="S" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
	<PinLayer side="E" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

####################################################################################
#  <PlacementBlockages>                                                            #
#     <Blockage name="blk_name" type="hard|soft|partial">                      #
#       <Attr density=1.2 excludeFlops=yes inst="inst_name" pushdown=yes fixed=yes/>      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                        #
#     </Blockage>                                                                  #
#  </PlacementBlockages>                                                           #
####################################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

##########################################################################################################################
#  <RouteBlockages>                                                                                                      #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">                                              #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes exceptpgnet=yes pgnetonly=yes coreeolblkg=yes blockeolblkg=yes/>  #
#       <Layer type="route|cut|masterslice" id=layerNo />                                                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                                                              #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                                                                      #
#     </Blockage>                                                                                                        #
#  </RouteBlockages>                                                                                                     #
##########################################################################################################################

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

###########################################################################################
# NetbottomPreferredRoutingLayer:  <net_name> <bottomPreferredRoutingLayer (in integer)>  #
###########################################################################################

################################################################
# NetAvoidDetour:  <net_name>  < avoidDetour  { 1| 0}>   #
################################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: riscv_pipeline_hierFP.fp.spr

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 BotMask=2 CutMask=1 TopMask=2 />...  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <NETEXPR>                                                             #
#        ground VSS                                                          #
#      </NETEXPR> ...                                                        #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="clk" >
  </Pin>
  <Pin name="reset_n" >
  </Pin>
  <Pin name="riscv_start" >
  </Pin>
  <Pin name="meip_i" >
  </Pin>
  <Pin name="msip_i" >
  </Pin>
  <Pin name="mtip_i" >
  </Pin>
  <Pin name="reset_vector_in[31]" >
  </Pin>
  <Pin name="reset_vector_in[30]" >
  </Pin>
  <Pin name="reset_vector_in[29]" >
  </Pin>
  <Pin name="reset_vector_in[28]" >
  </Pin>
  <Pin name="reset_vector_in[27]" >
  </Pin>
  <Pin name="reset_vector_in[26]" >
  </Pin>
  <Pin name="reset_vector_in[25]" >
  </Pin>
  <Pin name="reset_vector_in[24]" >
  </Pin>
  <Pin name="reset_vector_in[23]" >
  </Pin>
  <Pin name="reset_vector_in[22]" >
  </Pin>
  <Pin name="reset_vector_in[21]" >
  </Pin>
  <Pin name="reset_vector_in[20]" >
  </Pin>
  <Pin name="reset_vector_in[19]" >
  </Pin>
  <Pin name="reset_vector_in[18]" >
  </Pin>
  <Pin name="reset_vector_in[17]" >
  </Pin>
  <Pin name="reset_vector_in[16]" >
  </Pin>
  <Pin name="reset_vector_in[15]" >
  </Pin>
  <Pin name="reset_vector_in[14]" >
  </Pin>
  <Pin name="reset_vector_in[13]" >
  </Pin>
  <Pin name="reset_vector_in[12]" >
  </Pin>
  <Pin name="reset_vector_in[11]" >
  </Pin>
  <Pin name="reset_vector_in[10]" >
  </Pin>
  <Pin name="reset_vector_in[9]" >
  </Pin>
  <Pin name="reset_vector_in[8]" >
  </Pin>
  <Pin name="reset_vector_in[7]" >
  </Pin>
  <Pin name="reset_vector_in[6]" >
  </Pin>
  <Pin name="reset_vector_in[5]" >
  </Pin>
  <Pin name="reset_vector_in[4]" >
  </Pin>
  <Pin name="reset_vector_in[3]" >
  </Pin>
  <Pin name="reset_vector_in[2]" >
  </Pin>
  <Pin name="reset_vector_in[1]" >
  </Pin>
  <Pin name="reset_vector_in[0]" >
  </Pin>
  <Pin name="riscv_done" >
  </Pin>
  <Pin name="icache_read_req" >
  </Pin>
  <Pin name="icache_addr[31]" >
  </Pin>
  <Pin name="icache_addr[30]" >
  </Pin>
  <Pin name="icache_addr[29]" >
  </Pin>
  <Pin name="icache_addr[28]" >
  </Pin>
  <Pin name="icache_addr[27]" >
  </Pin>
  <Pin name="icache_addr[26]" >
  </Pin>
  <Pin name="icache_addr[25]" >
  </Pin>
  <Pin name="icache_addr[24]" >
  </Pin>
  <Pin name="icache_addr[23]" >
  </Pin>
  <Pin name="icache_addr[22]" >
  </Pin>
  <Pin name="icache_addr[21]" >
  </Pin>
  <Pin name="icache_addr[20]" >
  </Pin>
  <Pin name="icache_addr[19]" >
  </Pin>
  <Pin name="icache_addr[18]" >
  </Pin>
  <Pin name="icache_addr[17]" >
  </Pin>
  <Pin name="icache_addr[16]" >
  </Pin>
  <Pin name="icache_addr[15]" >
  </Pin>
  <Pin name="icache_addr[14]" >
  </Pin>
  <Pin name="icache_addr[13]" >
  </Pin>
  <Pin name="icache_addr[12]" >
  </Pin>
  <Pin name="icache_addr[11]" >
  </Pin>
  <Pin name="icache_addr[10]" >
  </Pin>
  <Pin name="icache_addr[9]" >
  </Pin>
  <Pin name="icache_addr[8]" >
  </Pin>
  <Pin name="icache_addr[7]" >
  </Pin>
  <Pin name="icache_addr[6]" >
  </Pin>
  <Pin name="icache_addr[5]" >
  </Pin>
  <Pin name="icache_addr[4]" >
  </Pin>
  <Pin name="icache_addr[3]" >
  </Pin>
  <Pin name="icache_addr[2]" >
  </Pin>
  <Pin name="icache_addr[1]" >
  </Pin>
  <Pin name="icache_addr[0]" >
  </Pin>
  <Pin name="icache_read_data[31]" >
  </Pin>
  <Pin name="icache_read_data[30]" >
  </Pin>
  <Pin name="icache_read_data[29]" >
  </Pin>
  <Pin name="icache_read_data[28]" >
  </Pin>
  <Pin name="icache_read_data[27]" >
  </Pin>
  <Pin name="icache_read_data[26]" >
  </Pin>
  <Pin name="icache_read_data[25]" >
  </Pin>
  <Pin name="icache_read_data[24]" >
  </Pin>
  <Pin name="icache_read_data[23]" >
  </Pin>
  <Pin name="icache_read_data[22]" >
  </Pin>
  <Pin name="icache_read_data[21]" >
  </Pin>
  <Pin name="icache_read_data[20]" >
  </Pin>
  <Pin name="icache_read_data[19]" >
  </Pin>
  <Pin name="icache_read_data[18]" >
  </Pin>
  <Pin name="icache_read_data[17]" >
  </Pin>
  <Pin name="icache_read_data[16]" >
  </Pin>
  <Pin name="icache_read_data[15]" >
  </Pin>
  <Pin name="icache_read_data[14]" >
  </Pin>
  <Pin name="icache_read_data[13]" >
  </Pin>
  <Pin name="icache_read_data[12]" >
  </Pin>
  <Pin name="icache_read_data[11]" >
  </Pin>
  <Pin name="icache_read_data[10]" >
  </Pin>
  <Pin name="icache_read_data[9]" >
  </Pin>
  <Pin name="icache_read_data[8]" >
  </Pin>
  <Pin name="icache_read_data[7]" >
  </Pin>
  <Pin name="icache_read_data[6]" >
  </Pin>
  <Pin name="icache_read_data[5]" >
  </Pin>
  <Pin name="icache_read_data[4]" >
  </Pin>
  <Pin name="icache_read_data[3]" >
  </Pin>
  <Pin name="icache_read_data[2]" >
  </Pin>
  <Pin name="icache_read_data[1]" >
  </Pin>
  <Pin name="icache_read_data[0]" >
  </Pin>
  <Pin name="icache_hit" >
  </Pin>
  <Pin name="icache_stall" >
  </Pin>
  <Pin name="dcache_read_req" >
  </Pin>
  <Pin name="dcache_write_req" >
  </Pin>
  <Pin name="dcache_addr[31]" >
  </Pin>
  <Pin name="dcache_addr[30]" >
  </Pin>
  <Pin name="dcache_addr[29]" >
  </Pin>
  <Pin name="dcache_addr[28]" >
  </Pin>
  <Pin name="dcache_addr[27]" >
  </Pin>
  <Pin name="dcache_addr[26]" >
  </Pin>
  <Pin name="dcache_addr[25]" >
  </Pin>
  <Pin name="dcache_addr[24]" >
  </Pin>
  <Pin name="dcache_addr[23]" >
  </Pin>
  <Pin name="dcache_addr[22]" >
  </Pin>
  <Pin name="dcache_addr[21]" >
  </Pin>
  <Pin name="dcache_addr[20]" >
  </Pin>
  <Pin name="dcache_addr[19]" >
  </Pin>
  <Pin name="dcache_addr[18]" >
  </Pin>
  <Pin name="dcache_addr[17]" >
  </Pin>
  <Pin name="dcache_addr[16]" >
  </Pin>
  <Pin name="dcache_addr[15]" >
  </Pin>
  <Pin name="dcache_addr[14]" >
  </Pin>
  <Pin name="dcache_addr[13]" >
  </Pin>
  <Pin name="dcache_addr[12]" >
  </Pin>
  <Pin name="dcache_addr[11]" >
  </Pin>
  <Pin name="dcache_addr[10]" >
  </Pin>
  <Pin name="dcache_addr[9]" >
  </Pin>
  <Pin name="dcache_addr[8]" >
  </Pin>
  <Pin name="dcache_addr[7]" >
  </Pin>
  <Pin name="dcache_addr[6]" >
  </Pin>
  <Pin name="dcache_addr[5]" >
  </Pin>
  <Pin name="dcache_addr[4]" >
  </Pin>
  <Pin name="dcache_addr[3]" >
  </Pin>
  <Pin name="dcache_addr[2]" >
  </Pin>
  <Pin name="dcache_addr[1]" >
  </Pin>
  <Pin name="dcache_addr[0]" >
  </Pin>
  <Pin name="dcache_write_data[31]" >
  </Pin>
  <Pin name="dcache_write_data[30]" >
  </Pin>
  <Pin name="dcache_write_data[29]" >
  </Pin>
  <Pin name="dcache_write_data[28]" >
  </Pin>
  <Pin name="dcache_write_data[27]" >
  </Pin>
  <Pin name="dcache_write_data[26]" >
  </Pin>
  <Pin name="dcache_write_data[25]" >
  </Pin>
  <Pin name="dcache_write_data[24]" >
  </Pin>
  <Pin name="dcache_write_data[23]" >
  </Pin>
  <Pin name="dcache_write_data[22]" >
  </Pin>
  <Pin name="dcache_write_data[21]" >
  </Pin>
  <Pin name="dcache_write_data[20]" >
  </Pin>
  <Pin name="dcache_write_data[19]" >
  </Pin>
  <Pin name="dcache_write_data[18]" >
  </Pin>
  <Pin name="dcache_write_data[17]" >
  </Pin>
  <Pin name="dcache_write_data[16]" >
  </Pin>
  <Pin name="dcache_write_data[15]" >
  </Pin>
  <Pin name="dcache_write_data[14]" >
  </Pin>
  <Pin name="dcache_write_data[13]" >
  </Pin>
  <Pin name="dcache_write_data[12]" >
  </Pin>
  <Pin name="dcache_write_data[11]" >
  </Pin>
  <Pin name="dcache_write_data[10]" >
  </Pin>
  <Pin name="dcache_write_data[9]" >
  </Pin>
  <Pin name="dcache_write_data[8]" >
  </Pin>
  <Pin name="dcache_write_data[7]" >
  </Pin>
  <Pin name="dcache_write_data[6]" >
  </Pin>
  <Pin name="dcache_write_data[5]" >
  </Pin>
  <Pin name="dcache_write_data[4]" >
  </Pin>
  <Pin name="dcache_write_data[3]" >
  </Pin>
  <Pin name="dcache_write_data[2]" >
  </Pin>
  <Pin name="dcache_write_data[1]" >
  </Pin>
  <Pin name="dcache_write_data[0]" >
  </Pin>
  <Pin name="dcache_read_data[31]" >
  </Pin>
  <Pin name="dcache_read_data[30]" >
  </Pin>
  <Pin name="dcache_read_data[29]" >
  </Pin>
  <Pin name="dcache_read_data[28]" >
  </Pin>
  <Pin name="dcache_read_data[27]" >
  </Pin>
  <Pin name="dcache_read_data[26]" >
  </Pin>
  <Pin name="dcache_read_data[25]" >
  </Pin>
  <Pin name="dcache_read_data[24]" >
  </Pin>
  <Pin name="dcache_read_data[23]" >
  </Pin>
  <Pin name="dcache_read_data[22]" >
  </Pin>
  <Pin name="dcache_read_data[21]" >
  </Pin>
  <Pin name="dcache_read_data[20]" >
  </Pin>
  <Pin name="dcache_read_data[19]" >
  </Pin>
  <Pin name="dcache_read_data[18]" >
  </Pin>
  <Pin name="dcache_read_data[17]" >
  </Pin>
  <Pin name="dcache_read_data[16]" >
  </Pin>
  <Pin name="dcache_read_data[15]" >
  </Pin>
  <Pin name="dcache_read_data[14]" >
  </Pin>
  <Pin name="dcache_read_data[13]" >
  </Pin>
  <Pin name="dcache_read_data[12]" >
  </Pin>
  <Pin name="dcache_read_data[11]" >
  </Pin>
  <Pin name="dcache_read_data[10]" >
  </Pin>
  <Pin name="dcache_read_data[9]" >
  </Pin>
  <Pin name="dcache_read_data[8]" >
  </Pin>
  <Pin name="dcache_read_data[7]" >
  </Pin>
  <Pin name="dcache_read_data[6]" >
  </Pin>
  <Pin name="dcache_read_data[5]" >
  </Pin>
  <Pin name="dcache_read_data[4]" >
  </Pin>
  <Pin name="dcache_read_data[3]" >
  </Pin>
  <Pin name="dcache_read_data[2]" >
  </Pin>
  <Pin name="dcache_read_data[1]" >
  </Pin>
  <Pin name="dcache_read_data[0]" >
  </Pin>
  <Pin name="dcache_hit" >
  </Pin>
  <Pin name="dcache_stall" >
  </Pin>
  <Pin name="mem_size_top[1]" >
  </Pin>
  <Pin name="mem_size_top[0]" >
  </Pin>
  <Pin name="mem_unsigned_top" >
  </Pin>
  <Pin name="wfi_sleep_out" >
  </Pin>
  <Pin name="dbg_halt_req" >
  </Pin>
  <Pin name="dbg_resume_req" >
  </Pin>
  <Pin name="dbg_halted" >
  </Pin>
  <Pin name="dbg_reg_read_addr[15]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[14]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[13]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[12]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[11]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[10]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[9]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[8]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[7]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[6]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[5]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[4]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[3]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[2]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[1]" >
  </Pin>
  <Pin name="dbg_reg_read_addr[0]" >
  </Pin>
  <Pin name="dbg_reg_read_data[31]" >
  </Pin>
  <Pin name="dbg_reg_read_data[30]" >
  </Pin>
  <Pin name="dbg_reg_read_data[29]" >
  </Pin>
  <Pin name="dbg_reg_read_data[28]" >
  </Pin>
  <Pin name="dbg_reg_read_data[27]" >
  </Pin>
  <Pin name="dbg_reg_read_data[26]" >
  </Pin>
  <Pin name="dbg_reg_read_data[25]" >
  </Pin>
  <Pin name="dbg_reg_read_data[24]" >
  </Pin>
  <Pin name="dbg_reg_read_data[23]" >
  </Pin>
  <Pin name="dbg_reg_read_data[22]" >
  </Pin>
  <Pin name="dbg_reg_read_data[21]" >
  </Pin>
  <Pin name="dbg_reg_read_data[20]" >
  </Pin>
  <Pin name="dbg_reg_read_data[19]" >
  </Pin>
  <Pin name="dbg_reg_read_data[18]" >
  </Pin>
  <Pin name="dbg_reg_read_data[17]" >
  </Pin>
  <Pin name="dbg_reg_read_data[16]" >
  </Pin>
  <Pin name="dbg_reg_read_data[15]" >
  </Pin>
  <Pin name="dbg_reg_read_data[14]" >
  </Pin>
  <Pin name="dbg_reg_read_data[13]" >
  </Pin>
  <Pin name="dbg_reg_read_data[12]" >
  </Pin>
  <Pin name="dbg_reg_read_data[11]" >
  </Pin>
  <Pin name="dbg_reg_read_data[10]" >
  </Pin>
  <Pin name="dbg_reg_read_data[9]" >
  </Pin>
  <Pin name="dbg_reg_read_data[8]" >
  </Pin>
  <Pin name="dbg_reg_read_data[7]" >
  </Pin>
  <Pin name="dbg_reg_read_data[6]" >
  </Pin>
  <Pin name="dbg_reg_read_data[5]" >
  </Pin>
  <Pin name="dbg_reg_read_data[4]" >
  </Pin>
  <Pin name="dbg_reg_read_data[3]" >
  </Pin>
  <Pin name="dbg_reg_read_data[2]" >
  </Pin>
  <Pin name="dbg_reg_read_data[1]" >
  </Pin>
  <Pin name="dbg_reg_read_data[0]" >
  </Pin>
  <Pin name="dbg_reg_write_en" >
  </Pin>
  <Pin name="dbg_reg_write_addr[15]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[14]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[13]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[12]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[11]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[10]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[9]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[8]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[7]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[6]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[5]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[4]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[3]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[2]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[1]" >
  </Pin>
  <Pin name="dbg_reg_write_addr[0]" >
  </Pin>
  <Pin name="dbg_reg_write_data[31]" >
  </Pin>
  <Pin name="dbg_reg_write_data[30]" >
  </Pin>
  <Pin name="dbg_reg_write_data[29]" >
  </Pin>
  <Pin name="dbg_reg_write_data[28]" >
  </Pin>
  <Pin name="dbg_reg_write_data[27]" >
  </Pin>
  <Pin name="dbg_reg_write_data[26]" >
  </Pin>
  <Pin name="dbg_reg_write_data[25]" >
  </Pin>
  <Pin name="dbg_reg_write_data[24]" >
  </Pin>
  <Pin name="dbg_reg_write_data[23]" >
  </Pin>
  <Pin name="dbg_reg_write_data[22]" >
  </Pin>
  <Pin name="dbg_reg_write_data[21]" >
  </Pin>
  <Pin name="dbg_reg_write_data[20]" >
  </Pin>
  <Pin name="dbg_reg_write_data[19]" >
  </Pin>
  <Pin name="dbg_reg_write_data[18]" >
  </Pin>
  <Pin name="dbg_reg_write_data[17]" >
  </Pin>
  <Pin name="dbg_reg_write_data[16]" >
  </Pin>
  <Pin name="dbg_reg_write_data[15]" >
  </Pin>
  <Pin name="dbg_reg_write_data[14]" >
  </Pin>
  <Pin name="dbg_reg_write_data[13]" >
  </Pin>
  <Pin name="dbg_reg_write_data[12]" >
  </Pin>
  <Pin name="dbg_reg_write_data[11]" >
  </Pin>
  <Pin name="dbg_reg_write_data[10]" >
  </Pin>
  <Pin name="dbg_reg_write_data[9]" >
  </Pin>
  <Pin name="dbg_reg_write_data[8]" >
  </Pin>
  <Pin name="dbg_reg_write_data[7]" >
  </Pin>
  <Pin name="dbg_reg_write_data[6]" >
  </Pin>
  <Pin name="dbg_reg_write_data[5]" >
  </Pin>
  <Pin name="dbg_reg_write_data[4]" >
  </Pin>
  <Pin name="dbg_reg_write_data[3]" >
  </Pin>
  <Pin name="dbg_reg_write_data[2]" >
  </Pin>
  <Pin name="dbg_reg_write_data[1]" >
  </Pin>
  <Pin name="dbg_reg_write_data[0]" >
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="riscv_pipeline">
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
